
connection: "pmdevpresto"


explore: dim_agent__2456af45_cc4f_44bd_a0f0_2d765c73c4c1 {

}


view: dim_agent__2456af45_cc4f_44bd_a0f0_2d765c73c4c1 {
sql_table_name:hive.isaktest.dim_agent ;;
dimension: agent_record_key {
 type: string
 sql: ${TABLE}.agent_record_key;;
}
dimension: agent_id {
 type: string
 sql: ${TABLE}.agent_id;;
}
dimension: csr_id {
 type: string
 sql: ${TABLE}.csr_id;;
}
dimension: agent_supervisor_record_key {
 type: string
 sql: ${TABLE}.agent_supervisor_record_key;;
}
dimension: agent_supervisor_csr_id {
 type: string
 sql: ${TABLE}.agent_supervisor_csr_id;;
}
dimension: agent_status {
 type: string
 sql: ${TABLE}.agent_status;;
}
dimension: agent_role_start_date {
 type: string
 sql: ${TABLE}.agent_role_start_date;;
}
dimension: agent_role_end_date {
 type: string
 sql: ${TABLE}.agent_role_end_date;;
}
dimension: agent_role_sms {
 type: string
 sql: ${TABLE}.agent_role_sms;;
}
dimension: agent_role_marketing {
 type: string
 sql: ${TABLE}.agent_role_marketing;;
}
dimension: agent_location {
 type: string
 sql: ${TABLE}.agent_location;;
}
dimension: agent_vendor {
 type: string
 sql: ${TABLE}.agent_vendor;;
}
dimension: agent_site {
 type: string
 sql: ${TABLE}.agent_site;;
}
dimension: agent_lob {
 type: string
 sql: ${TABLE}.agent_lob;;
}
dimension: activation_source {
 type: string
 sql: ${TABLE}.activation_source;;
}
dimension: current_record_flag {
 type: string
 sql: ${TABLE}.current_record_flag;;
}
dimension: deleted_record_flag {
 type: string
 sql: ${TABLE}.deleted_record_flag;;
}
dimension: col17 {
 type: string
 sql: ${TABLE}.col17;;
}
}


view: PERMISSIONSET__c59dcac8_d27b_4ecc_88f9_093619791bcd {
sql_table_name:sforce.SFORCE.PERMISSIONSET ;;
dimension: ID {
 type: string
 sql: ${TABLE}.ID;;
}
dimension: NAME {
 type: string
 sql: ${TABLE}.NAME;;
}
dimension: LABEL {
 type: string
 sql: ${TABLE}.LABEL;;
}
dimension: LICENSEID {
 type: string
 sql: ${TABLE}.LICENSEID;;
}
dimension: PROFILEID {
 type: string
 sql: ${TABLE}.PROFILEID;;
}
dimension: ISOWNEDBYPROFILE {
 type: string
 sql: ${TABLE}.ISOWNEDBYPROFILE;;
}
dimension: ISCUSTOM {
 type: string
 sql: ${TABLE}.ISCUSTOM;;
}
dimension: PERMISSIONSEMAILSINGLE {
 type: string
 sql: ${TABLE}.PERMISSIONSEMAILSINGLE;;
}
dimension: PERMISSIONSEMAILMASS {
 type: string
 sql: ${TABLE}.PERMISSIONSEMAILMASS;;
}
dimension: PERMISSIONSEDITTASK {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITTASK;;
}
dimension: PERMISSIONSEDITEVENT {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITEVENT;;
}
dimension: PERMISSIONSEXPORTREPORT {
 type: string
 sql: ${TABLE}.PERMISSIONSEXPORTREPORT;;
}
dimension: PERMISSIONSIMPORTPERSONAL {
 type: string
 sql: ${TABLE}.PERMISSIONSIMPORTPERSONAL;;
}
dimension: PERMISSIONSDATAEXPORT {
 type: string
 sql: ${TABLE}.PERMISSIONSDATAEXPORT;;
}
dimension: PERMISSIONSMANAGEUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEUSERS;;
}
dimension: PERMISSIONSEDITPUBLICFILTERS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITPUBLICFILTERS;;
}
dimension: PERMISSIONSEDITPUBLICTEMPLATES {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITPUBLICTEMPLATES;;
}
dimension: PERMISSIONSMODIFYALLDATA {
 type: string
 sql: ${TABLE}.PERMISSIONSMODIFYALLDATA;;
}
dimension: PERMISSIONSMANAGECASES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECASES;;
}
dimension: PERMISSIONSMASSINLINEEDIT {
 type: string
 sql: ${TABLE}.PERMISSIONSMASSINLINEEDIT;;
}
dimension: PERMISSIONSEDITKNOWLEDGE {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITKNOWLEDGE;;
}
dimension: PERMISSIONSMANAGEKNOWLEDGE {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEKNOWLEDGE;;
}
dimension: PERMISSIONSMANAGESOLUTIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESOLUTIONS;;
}
dimension: PERMISSIONSCUSTOMIZEAPPLICATION {
 type: string
 sql: ${TABLE}.PERMISSIONSCUSTOMIZEAPPLICATION;;
}
dimension: PERMISSIONSEDITREADONLYFIELDS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITREADONLYFIELDS;;
}
dimension: PERMISSIONSRUNREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSRUNREPORTS;;
}
dimension: PERMISSIONSVIEWSETUP {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWSETUP;;
}
dimension: PERMISSIONSTRANSFERANYENTITY {
 type: string
 sql: ${TABLE}.PERMISSIONSTRANSFERANYENTITY;;
}
dimension: PERMISSIONSNEWREPORTBUILDER {
 type: string
 sql: ${TABLE}.PERMISSIONSNEWREPORTBUILDER;;
}
dimension: PERMISSIONSACTIVATECONTRACT {
 type: string
 sql: ${TABLE}.PERMISSIONSACTIVATECONTRACT;;
}
dimension: PERMISSIONSACTIVATEORDER {
 type: string
 sql: ${TABLE}.PERMISSIONSACTIVATEORDER;;
}
dimension: PERMISSIONSIMPORTLEADS {
 type: string
 sql: ${TABLE}.PERMISSIONSIMPORTLEADS;;
}
dimension: PERMISSIONSMANAGELEADS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGELEADS;;
}
dimension: PERMISSIONSTRANSFERANYLEAD {
 type: string
 sql: ${TABLE}.PERMISSIONSTRANSFERANYLEAD;;
}
dimension: PERMISSIONSVIEWALLDATA {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWALLDATA;;
}
dimension: PERMISSIONSEDITPUBLICDOCUMENTS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITPUBLICDOCUMENTS;;
}
dimension: PERMISSIONSCONTENTHUBONPREMISEUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSCONTENTHUBONPREMISEUSER;;
}
dimension: PERMISSIONSVIEWENCRYPTEDDATA {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWENCRYPTEDDATA;;
}
dimension: PERMISSIONSEDITBRANDTEMPLATES {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITBRANDTEMPLATES;;
}
dimension: PERMISSIONSEDITHTMLTEMPLATES {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITHTMLTEMPLATES;;
}
dimension: PERMISSIONSCHATTERINTERNALUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTERINTERNALUSER;;
}
dimension: PERMISSIONSMANAGEENCRYPTIONKEYS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEENCRYPTIONKEYS;;
}
dimension: PERMISSIONSDELETEACTIVATEDCONTRACT {
 type: string
 sql: ${TABLE}.PERMISSIONSDELETEACTIVATEDCONTRACT;;
}
dimension: PERMISSIONSCHATTERINVITEEXTERNALUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTERINVITEEXTERNALUSERS;;
}
dimension: PERMISSIONSSENDSITREQUESTS {
 type: string
 sql: ${TABLE}.PERMISSIONSSENDSITREQUESTS;;
}
dimension: PERMISSIONSMANAGEREMOTEACCESS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEREMOTEACCESS;;
}
dimension: PERMISSIONSCANUSENEWDASHBOARDBUILDER {
 type: string
 sql: ${TABLE}.PERMISSIONSCANUSENEWDASHBOARDBUILDER;;
}
dimension: PERMISSIONSMANAGECATEGORIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECATEGORIES;;
}
dimension: PERMISSIONSCONVERTLEADS {
 type: string
 sql: ${TABLE}.PERMISSIONSCONVERTLEADS;;
}
dimension: PERMISSIONSPASSWORDNEVEREXPIRES {
 type: string
 sql: ${TABLE}.PERMISSIONSPASSWORDNEVEREXPIRES;;
}
dimension: PERMISSIONSUSETEAMREASSIGNWIZARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSUSETEAMREASSIGNWIZARDS;;
}
dimension: PERMISSIONSEDITACTIVATEDORDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITACTIVATEDORDERS;;
}
dimension: PERMISSIONSINSTALLPACKAGING {
 type: string
 sql: ${TABLE}.PERMISSIONSINSTALLPACKAGING;;
}
dimension: PERMISSIONSPUBLISHPACKAGING {
 type: string
 sql: ${TABLE}.PERMISSIONSPUBLISHPACKAGING;;
}
dimension: PERMISSIONSCHATTEROWNGROUPS {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTEROWNGROUPS;;
}
dimension: PERMISSIONSEDITOPPLINEITEMUNITPRICE {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITOPPLINEITEMUNITPRICE;;
}
dimension: PERMISSIONSCREATEPACKAGING {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEPACKAGING;;
}
dimension: PERMISSIONSBULKAPIHARDDELETE {
 type: string
 sql: ${TABLE}.PERMISSIONSBULKAPIHARDDELETE;;
}
dimension: PERMISSIONSSOLUTIONIMPORT {
 type: string
 sql: ${TABLE}.PERMISSIONSSOLUTIONIMPORT;;
}
dimension: PERMISSIONSMANAGECALLCENTERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECALLCENTERS;;
}
dimension: PERMISSIONSMANAGESYNONYMS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESYNONYMS;;
}
dimension: PERMISSIONSVIEWCONTENT {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWCONTENT;;
}
dimension: PERMISSIONSMANAGEEMAILCLIENTCONFIG {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEEMAILCLIENTCONFIG;;
}
dimension: PERMISSIONSENABLENOTIFICATIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSENABLENOTIFICATIONS;;
}
dimension: PERMISSIONSMANAGEDATAINTEGRATIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEDATAINTEGRATIONS;;
}
dimension: PERMISSIONSDISTRIBUTEFROMPERSWKSP {
 type: string
 sql: ${TABLE}.PERMISSIONSDISTRIBUTEFROMPERSWKSP;;
}
dimension: PERMISSIONSVIEWDATACATEGORIES {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWDATACATEGORIES;;
}
dimension: PERMISSIONSMANAGEDATACATEGORIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEDATACATEGORIES;;
}
dimension: PERMISSIONSAUTHORAPEX {
 type: string
 sql: ${TABLE}.PERMISSIONSAUTHORAPEX;;
}
dimension: PERMISSIONSMANAGEMOBILE {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEMOBILE;;
}
dimension: PERMISSIONSAPIENABLED {
 type: string
 sql: ${TABLE}.PERMISSIONSAPIENABLED;;
}
dimension: PERMISSIONSMANAGECUSTOMREPORTTYPES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECUSTOMREPORTTYPES;;
}
dimension: PERMISSIONSEDITCASECOMMENTS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITCASECOMMENTS;;
}
dimension: PERMISSIONSTRANSFERANYCASE {
 type: string
 sql: ${TABLE}.PERMISSIONSTRANSFERANYCASE;;
}
dimension: PERMISSIONSCONTENTADMINISTRATOR {
 type: string
 sql: ${TABLE}.PERMISSIONSCONTENTADMINISTRATOR;;
}
dimension: PERMISSIONSCREATEWORKSPACES {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEWORKSPACES;;
}
dimension: PERMISSIONSMANAGECONTENTPERMISSIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTPERMISSIONS;;
}
dimension: PERMISSIONSMANAGECONTENTPROPERTIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTPROPERTIES;;
}
dimension: PERMISSIONSMANAGECONTENTTYPES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTTYPES;;
}
dimension: PERMISSIONSMANAGEEXCHANGECONFIG {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEEXCHANGECONFIG;;
}
dimension: PERMISSIONSMANAGEANALYTICSNAPSHOTS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEANALYTICSNAPSHOTS;;
}
dimension: PERMISSIONSSCHEDULEREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSSCHEDULEREPORTS;;
}
dimension: PERMISSIONSMANAGEBUSINESSHOURHOLIDAYS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEBUSINESSHOURHOLIDAYS;;
}
dimension: PERMISSIONSMANAGEDYNAMICDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEDYNAMICDASHBOARDS;;
}
dimension: PERMISSIONSCUSTOMSIDEBARONALLPAGES {
 type: string
 sql: ${TABLE}.PERMISSIONSCUSTOMSIDEBARONALLPAGES;;
}
dimension: PERMISSIONSMANAGEINTERACTION {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEINTERACTION;;
}
dimension: PERMISSIONSVIEWMYTEAMSDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWMYTEAMSDASHBOARDS;;
}
dimension: PERMISSIONSMODERATECHATTER {
 type: string
 sql: ${TABLE}.PERMISSIONSMODERATECHATTER;;
}
dimension: PERMISSIONSRESETPASSWORDS {
 type: string
 sql: ${TABLE}.PERMISSIONSRESETPASSWORDS;;
}
dimension: PERMISSIONSFLOWUFLREQUIRED {
 type: string
 sql: ${TABLE}.PERMISSIONSFLOWUFLREQUIRED;;
}
dimension: PERMISSIONSCANINSERTFEEDSYSTEMFIELDS {
 type: string
 sql: ${TABLE}.PERMISSIONSCANINSERTFEEDSYSTEMFIELDS;;
}
dimension: PERMISSIONSACTIVITIESACCESS {
 type: string
 sql: ${TABLE}.PERMISSIONSACTIVITIESACCESS;;
}
dimension: PERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT;;
}
dimension: PERMISSIONSEMAILTEMPLATEMANAGEMENT {
 type: string
 sql: ${TABLE}.PERMISSIONSEMAILTEMPLATEMANAGEMENT;;
}
dimension: PERMISSIONSEMAILADMINISTRATION {
 type: string
 sql: ${TABLE}.PERMISSIONSEMAILADMINISTRATION;;
}
dimension: PERMISSIONSMANAGECHATTERMESSAGES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECHATTERMESSAGES;;
}
dimension: PERMISSIONSALLOWEMAILIC {
 type: string
 sql: ${TABLE}.PERMISSIONSALLOWEMAILIC;;
}
dimension: PERMISSIONSCHATTERFILELINK {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTERFILELINK;;
}
dimension: PERMISSIONSFORCETWOFACTOR {
 type: string
 sql: ${TABLE}.PERMISSIONSFORCETWOFACTOR;;
}
dimension: PERMISSIONSVIEWEVENTLOGFILES {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWEVENTLOGFILES;;
}
dimension: PERMISSIONSMANAGENETWORKS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGENETWORKS;;
}
dimension: PERMISSIONSMANAGEAUTHPROVIDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEAUTHPROVIDERS;;
}
dimension: PERMISSIONSRUNFLOW {
 type: string
 sql: ${TABLE}.PERMISSIONSRUNFLOW;;
}
dimension: PERMISSIONSCREATECUSTOMIZEDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEDASHBOARDS;;
}
dimension: PERMISSIONSCREATEDASHBOARDFOLDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEDASHBOARDFOLDERS;;
}
dimension: PERMISSIONSVIEWPUBLICDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWPUBLICDASHBOARDS;;
}
dimension: PERMISSIONSMANAGEDASHBDSINPUBFOLDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEDASHBDSINPUBFOLDERS;;
}
dimension: PERMISSIONSCREATECUSTOMIZEREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEREPORTS;;
}
dimension: PERMISSIONSCREATEREPORTFOLDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEREPORTFOLDERS;;
}
dimension: PERMISSIONSVIEWPUBLICREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWPUBLICREPORTS;;
}
dimension: PERMISSIONSMANAGEREPORTSINPUBFOLDERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEREPORTSINPUBFOLDERS;;
}
dimension: PERMISSIONSEDITMYDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITMYDASHBOARDS;;
}
dimension: PERMISSIONSEDITMYREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITMYREPORTS;;
}
dimension: PERMISSIONSVIEWALLUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWALLUSERS;;
}
dimension: PERMISSIONSALLOWUNIVERSALSEARCH {
 type: string
 sql: ${TABLE}.PERMISSIONSALLOWUNIVERSALSEARCH;;
}
dimension: PERMISSIONSCONNECTORGTOENVIRONMENTHUB {
 type: string
 sql: ${TABLE}.PERMISSIONSCONNECTORGTOENVIRONMENTHUB;;
}
dimension: PERMISSIONSWORKCALIBRATIONUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSWORKCALIBRATIONUSER;;
}
dimension: PERMISSIONSCREATECUSTOMIZEFILTERS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEFILTERS;;
}
dimension: PERMISSIONSWORKDOTCOMUSERPERM {
 type: string
 sql: ${TABLE}.PERMISSIONSWORKDOTCOMUSERPERM;;
}
dimension: PERMISSIONSCONTENTHUBUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSCONTENTHUBUSER;;
}
dimension: PERMISSIONSGOVERNNETWORKS {
 type: string
 sql: ${TABLE}.PERMISSIONSGOVERNNETWORKS;;
}
dimension: PERMISSIONSSALESCONSOLE {
 type: string
 sql: ${TABLE}.PERMISSIONSSALESCONSOLE;;
}
dimension: PERMISSIONSTWOFACTORAPI {
 type: string
 sql: ${TABLE}.PERMISSIONSTWOFACTORAPI;;
}
dimension: PERMISSIONSDELETETOPICS {
 type: string
 sql: ${TABLE}.PERMISSIONSDELETETOPICS;;
}
dimension: PERMISSIONSEDITTOPICS {
 type: string
 sql: ${TABLE}.PERMISSIONSEDITTOPICS;;
}
dimension: PERMISSIONSCREATETOPICS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATETOPICS;;
}
dimension: PERMISSIONSASSIGNTOPICS {
 type: string
 sql: ${TABLE}.PERMISSIONSASSIGNTOPICS;;
}
dimension: PERMISSIONSIDENTITYENABLED {
 type: string
 sql: ${TABLE}.PERMISSIONSIDENTITYENABLED;;
}
dimension: PERMISSIONSIDENTITYCONNECT {
 type: string
 sql: ${TABLE}.PERMISSIONSIDENTITYCONNECT;;
}
dimension: PERMISSIONSALLOWVIEWKNOWLEDGE {
 type: string
 sql: ${TABLE}.PERMISSIONSALLOWVIEWKNOWLEDGE;;
}
dimension: PERMISSIONSCONTENTWORKSPACES {
 type: string
 sql: ${TABLE}.PERMISSIONSCONTENTWORKSPACES;;
}
dimension: PERMISSIONSMANAGESEARCHPROMOTIONRULES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESEARCHPROMOTIONRULES;;
}
dimension: PERMISSIONSCUSTOMMOBILEAPPSACCESS {
 type: string
 sql: ${TABLE}.PERMISSIONSCUSTOMMOBILEAPPSACCESS;;
}
dimension: PERMISSIONSVIEWHELPLINK {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWHELPLINK;;
}
dimension: PERMISSIONSMANAGEPROFILESPERMISSIONSETS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEPROFILESPERMISSIONSETS;;
}
dimension: PERMISSIONSASSIGNPERMISSIONSETS {
 type: string
 sql: ${TABLE}.PERMISSIONSASSIGNPERMISSIONSETS;;
}
dimension: PERMISSIONSMANAGEROLES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEROLES;;
}
dimension: PERMISSIONSMANAGEIPADDRESSES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEIPADDRESSES;;
}
dimension: PERMISSIONSMANAGESHARING {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESHARING;;
}
dimension: PERMISSIONSMANAGEINTERNALUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEINTERNALUSERS;;
}
dimension: PERMISSIONSMANAGEPASSWORDPOLICIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEPASSWORDPOLICIES;;
}
dimension: PERMISSIONSMANAGELOGINACCESSPOLICIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGELOGINACCESSPOLICIES;;
}
dimension: PERMISSIONSVIEWPLATFORMEVENTS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWPLATFORMEVENTS;;
}
dimension: PERMISSIONSMANAGECUSTOMPERMISSIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECUSTOMPERMISSIONS;;
}
dimension: PERMISSIONSCANVERIFYCOMMENT {
 type: string
 sql: ${TABLE}.PERMISSIONSCANVERIFYCOMMENT;;
}
dimension: PERMISSIONSMANAGEUNLISTEDGROUPS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEUNLISTEDGROUPS;;
}
dimension: PERMISSIONSSTDAUTOMATICACTIVITYCAPTURE {
 type: string
 sql: ${TABLE}.PERMISSIONSSTDAUTOMATICACTIVITYCAPTURE;;
}
dimension: PERMISSIONSMODIFYSECUREAGENTS {
 type: string
 sql: ${TABLE}.PERMISSIONSMODIFYSECUREAGENTS;;
}
dimension: PERMISSIONSINSIGHTSAPPDASHBOARDEDITOR {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPDASHBOARDEDITOR;;
}
dimension: PERMISSIONSMANAGETWOFACTOR {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGETWOFACTOR;;
}
dimension: PERMISSIONSINSIGHTSAPPUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPUSER;;
}
dimension: PERMISSIONSINSIGHTSAPPADMIN {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPADMIN;;
}
dimension: PERMISSIONSINSIGHTSAPPELTEDITOR {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPELTEDITOR;;
}
dimension: PERMISSIONSINSIGHTSAPPUPLOADUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPUPLOADUSER;;
}
dimension: PERMISSIONSINSIGHTSCREATEAPPLICATION {
 type: string
 sql: ${TABLE}.PERMISSIONSINSIGHTSCREATEAPPLICATION;;
}
dimension: PERMISSIONSLIGHTNINGEXPERIENCEUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSLIGHTNINGEXPERIENCEUSER;;
}
dimension: PERMISSIONSVIEWDATALEAKAGEEVENTS {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWDATALEAKAGEEVENTS;;
}
dimension: PERMISSIONSCONFIGCUSTOMRECS {
 type: string
 sql: ${TABLE}.PERMISSIONSCONFIGCUSTOMRECS;;
}
dimension: PERMISSIONSSUBMITMACROSALLOWED {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBMITMACROSALLOWED;;
}
dimension: PERMISSIONSBULKMACROSALLOWED {
 type: string
 sql: ${TABLE}.PERMISSIONSBULKMACROSALLOWED;;
}
dimension: PERMISSIONSSHAREINTERNALARTICLES {
 type: string
 sql: ${TABLE}.PERMISSIONSSHAREINTERNALARTICLES;;
}
dimension: PERMISSIONSMANAGESESSIONPERMISSIONSETS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESESSIONPERMISSIONSETS;;
}
dimension: PERMISSIONSMANAGETEMPLATEDAPP {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGETEMPLATEDAPP;;
}
dimension: PERMISSIONSUSETEMPLATEDAPP {
 type: string
 sql: ${TABLE}.PERMISSIONSUSETEMPLATEDAPP;;
}
dimension: PERMISSIONSSENDANNOUNCEMENTEMAILS {
 type: string
 sql: ${TABLE}.PERMISSIONSSENDANNOUNCEMENTEMAILS;;
}
dimension: PERMISSIONSCHATTEREDITOWNPOST {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTEREDITOWNPOST;;
}
dimension: PERMISSIONSCHATTEREDITOWNRECORDPOST {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTEREDITOWNRECORDPOST;;
}
dimension: PERMISSIONSSALESANALYTICSUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSSALESANALYTICSUSER;;
}
dimension: PERMISSIONSADMINANALYTICSUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSADMINANALYTICSUSER;;
}
dimension: PERMISSIONSSERVICEANALYTICSUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSSERVICEANALYTICSUSER;;
}
dimension: PERMISSIONSCREATEAUDITFIELDS {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEAUDITFIELDS;;
}
dimension: PERMISSIONSUPDATEWITHINACTIVEOWNER {
 type: string
 sql: ${TABLE}.PERMISSIONSUPDATEWITHINACTIVEOWNER;;
}
dimension: PERMISSIONSWAVETABULARDOWNLOAD {
 type: string
 sql: ${TABLE}.PERMISSIONSWAVETABULARDOWNLOAD;;
}
dimension: PERMISSIONSAUTOMATICACTIVITYCAPTURE {
 type: string
 sql: ${TABLE}.PERMISSIONSAUTOMATICACTIVITYCAPTURE;;
}
dimension: PERMISSIONSIMPORTCUSTOMOBJECTS {
 type: string
 sql: ${TABLE}.PERMISSIONSIMPORTCUSTOMOBJECTS;;
}
dimension: PERMISSIONSDELEGATEDTWOFACTOR {
 type: string
 sql: ${TABLE}.PERMISSIONSDELEGATEDTWOFACTOR;;
}
dimension: PERMISSIONSCHATTERCOMPOSEUICODESNIPPET {
 type: string
 sql: ${TABLE}.PERMISSIONSCHATTERCOMPOSEUICODESNIPPET;;
}
dimension: PERMISSIONSSELECTFILESFROMSALESFORCE {
 type: string
 sql: ${TABLE}.PERMISSIONSSELECTFILESFROMSALESFORCE;;
}
dimension: PERMISSIONSMODERATENETWORKUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSMODERATENETWORKUSERS;;
}
dimension: PERMISSIONSMERGETOPICS {
 type: string
 sql: ${TABLE}.PERMISSIONSMERGETOPICS;;
}
dimension: PERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS;;
}
dimension: PERMISSIONSMANAGEPVTRPTSANDDASHBDS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEPVTRPTSANDDASHBDS;;
}
dimension: PERMISSIONSALLOWLIGHTNINGLOGIN {
 type: string
 sql: ${TABLE}.PERMISSIONSALLOWLIGHTNINGLOGIN;;
}
dimension: PERMISSIONSCAMPAIGNINFLUENCE2 {
 type: string
 sql: ${TABLE}.PERMISSIONSCAMPAIGNINFLUENCE2;;
}
dimension: PERMISSIONSVIEWDATAASSESSMENT {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWDATAASSESSMENT;;
}
dimension: PERMISSIONSREMOVEDIRECTMESSAGEMEMBERS {
 type: string
 sql: ${TABLE}.PERMISSIONSREMOVEDIRECTMESSAGEMEMBERS;;
}
dimension: PERMISSIONSCANAPPROVEFEEDPOST {
 type: string
 sql: ${TABLE}.PERMISSIONSCANAPPROVEFEEDPOST;;
}
dimension: PERMISSIONSADDDIRECTMESSAGEMEMBERS {
 type: string
 sql: ${TABLE}.PERMISSIONSADDDIRECTMESSAGEMEMBERS;;
}
dimension: PERMISSIONSALLOWVIEWEDITCONVERTEDLEADS {
 type: string
 sql: ${TABLE}.PERMISSIONSALLOWVIEWEDITCONVERTEDLEADS;;
}
dimension: PERMISSIONSSHOWCOMPANYNAMEASUSERBADGE {
 type: string
 sql: ${TABLE}.PERMISSIONSSHOWCOMPANYNAMEASUSERBADGE;;
}
dimension: PERMISSIONSACCESSCMC {
 type: string
 sql: ${TABLE}.PERMISSIONSACCESSCMC;;
}
dimension: PERMISSIONSVIEWHEALTHCHECK {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWHEALTHCHECK;;
}
dimension: PERMISSIONSMANAGEHEALTHCHECK {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEHEALTHCHECK;;
}
dimension: PERMISSIONSPACKAGING2 {
 type: string
 sql: ${TABLE}.PERMISSIONSPACKAGING2;;
}
dimension: PERMISSIONSMANAGECERTIFICATES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGECERTIFICATES;;
}
dimension: PERMISSIONSCREATEREPORTINLIGHTNING {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEREPORTINLIGHTNING;;
}
dimension: PERMISSIONSPREVENTCLASSICEXPERIENCE {
 type: string
 sql: ${TABLE}.PERMISSIONSPREVENTCLASSICEXPERIENCE;;
}
dimension: PERMISSIONSHIDEREADBYLIST {
 type: string
 sql: ${TABLE}.PERMISSIONSHIDEREADBYLIST;;
}
dimension: PERMISSIONSUSESMARTDATADISCOVERY {
 type: string
 sql: ${TABLE}.PERMISSIONSUSESMARTDATADISCOVERY;;
}
dimension: PERMISSIONSGETSMARTDATADISCOVERY {
 type: string
 sql: ${TABLE}.PERMISSIONSGETSMARTDATADISCOVERY;;
}
dimension: PERMISSIONSCREATEUPDATESDDDATASET {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEUPDATESDDDATASET;;
}
dimension: PERMISSIONSCREATEUPDATESDDSTORY {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATEUPDATESDDSTORY;;
}
dimension: PERMISSIONSMANAGESMARTDATADISCOVERY {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESMARTDATADISCOVERY;;
}
dimension: PERMISSIONSSHARESMARTDATADISCOVERYSTORY {
 type: string
 sql: ${TABLE}.PERMISSIONSSHARESMARTDATADISCOVERYSTORY;;
}
dimension: PERMISSIONSMANAGESMARTDATADISCOVERYMODEL {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESMARTDATADISCOVERYMODEL;;
}
dimension: PERMISSIONSLISTEMAILSEND {
 type: string
 sql: ${TABLE}.PERMISSIONSLISTEMAILSEND;;
}
dimension: PERMISSIONSFEEDPINNING {
 type: string
 sql: ${TABLE}.PERMISSIONSFEEDPINNING;;
}
dimension: PERMISSIONSCHANGEDASHBOARDCOLORS {
 type: string
 sql: ${TABLE}.PERMISSIONSCHANGEDASHBOARDCOLORS;;
}
dimension: PERMISSIONSIOTUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSIOTUSER;;
}
dimension: PERMISSIONSMANAGERECOMMENDATIONSTRATEGIES {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGERECOMMENDATIONSTRATEGIES;;
}
dimension: PERMISSIONSMANAGEPROPOSITIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGEPROPOSITIONS;;
}
dimension: PERMISSIONSCLOSECONVERSATIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSCLOSECONVERSATIONS;;
}
dimension: PERMISSIONSUSEWEBLINK {
 type: string
 sql: ${TABLE}.PERMISSIONSUSEWEBLINK;;
}
dimension: PERMISSIONSVIEWONLYEMBEDDEDAPPUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWONLYEMBEDDEDAPPUSER;;
}
dimension: PERMISSIONSVIEWALLACTIVITIES {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWALLACTIVITIES;;
}
dimension: PERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS;;
}
dimension: PERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER;;
}
dimension: PERMISSIONSSUBSCRIBEREPORTSRUNASUSER {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEREPORTSRUNASUSER;;
}
dimension: PERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS;;
}
dimension: PERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS {
 type: string
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS;;
}
dimension: PERMISSIONSCREATELTNGTEMPINPUB {
 type: string
 sql: ${TABLE}.PERMISSIONSCREATELTNGTEMPINPUB;;
}
dimension: PERMISSIONSAPEXRESTSERVICES {
 type: string
 sql: ${TABLE}.PERMISSIONSAPEXRESTSERVICES;;
}
dimension: PERMISSIONSENABLECOMMUNITYAPPLAUNCHER {
 type: string
 sql: ${TABLE}.PERMISSIONSENABLECOMMUNITYAPPLAUNCHER;;
}
dimension: PERMISSIONSGIVERECOGNITIONBADGE {
 type: string
 sql: ${TABLE}.PERMISSIONSGIVERECOGNITIONBADGE;;
}
dimension: PERMISSIONSLTNGPROMORESERVED01USERPERM {
 type: string
 sql: ${TABLE}.PERMISSIONSLTNGPROMORESERVED01USERPERM;;
}
dimension: PERMISSIONSCANEDITDATAPREPRECIPE {
 type: string
 sql: ${TABLE}.PERMISSIONSCANEDITDATAPREPRECIPE;;
}
dimension: PERMISSIONSADDANALYTICSREMOTECONNECTIONS {
 type: string
 sql: ${TABLE}.PERMISSIONSADDANALYTICSREMOTECONNECTIONS;;
}
dimension: PERMISSIONSMANAGESURVEYS {
 type: string
 sql: ${TABLE}.PERMISSIONSMANAGESURVEYS;;
}
dimension: PERMISSIONSRECORDVISIBILITYAPI {
 type: string
 sql: ${TABLE}.PERMISSIONSRECORDVISIBILITYAPI;;
}
dimension: PERMISSIONSVIEWROLES {
 type: string
 sql: ${TABLE}.PERMISSIONSVIEWROLES;;
}
dimension: PERMISSIONSCANMANAGEMAPS {
 type: string
 sql: ${TABLE}.PERMISSIONSCANMANAGEMAPS;;
}
dimension: PERMISSIONSSTORYONDSWITHPREDICATE {
 type: string
 sql: ${TABLE}.PERMISSIONSSTORYONDSWITHPREDICATE;;
}
dimension: PERMISSIONSPRIVACYDATAACCESS {
 type: string
 sql: ${TABLE}.PERMISSIONSPRIVACYDATAACCESS;;
}
dimension: PERMISSIONSMODIFYMETADATA {
 type: string
 sql: ${TABLE}.PERMISSIONSMODIFYMETADATA;;
}
dimension: DESCRIPTION {
 type: string
 sql: ${TABLE}.DESCRIPTION;;
}
dimension: CREATEDDATE {
 type: string
 sql: ${TABLE}.CREATEDDATE;;
}
dimension: CREATEDBYID {
 type: string
 sql: ${TABLE}.CREATEDBYID;;
}
dimension: LASTMODIFIEDDATE {
 type: string
 sql: ${TABLE}.LASTMODIFIEDDATE;;
}
dimension: LASTMODIFIEDBYID {
 type: string
 sql: ${TABLE}.LASTMODIFIEDBYID;;
}
dimension: SYSTEMMODSTAMP {
 type: string
 sql: ${TABLE}.SYSTEMMODSTAMP;;
}
dimension: NAMESPACEPREFIX {
 type: string
 sql: ${TABLE}.NAMESPACEPREFIX;;
}
dimension: HASACTIVATIONREQUIRED {
 type: string
 sql: ${TABLE}.HASACTIVATIONREQUIRED;;
}
dimension: PERMISSIONSETGROUPID {
 type: string
 sql: ${TABLE}.PERMISSIONSETGROUPID;;
}
}