
connection:"presto-qa-1"


explore: PERMISSIONSETLICENSE__3255c177_aafa_41c2_b23b_ca970a94376d {

join: PROFILE__e99f63c3_ea19_46a8_8f3d_aba09d087ce9 {
 relationship: one_to_one
 sql_on: ${PERMISSIONSETLICENSE__3255c177_aafa_41c2_b23b_ca970a94376d.ID} = ${PROFILE__e99f63c3_ea19_46a8_8f3d_aba09d087ce9.ID} ;;
}
}


view: PERMISSIONSETLICENSE__3255c177_aafa_41c2_b23b_ca970a94376d {
sql_table_name:sforce.SFORCE.PERMISSIONSETLICENSE ;;
dimension: ID {
 sql: ${TABLE}.ID;;
}
dimension: ISDELETED {
 sql: ${TABLE}.ISDELETED;;
}
dimension: DEVELOPERNAME {
 sql: ${TABLE}.DEVELOPERNAME;;
}
dimension: LANGUAGENULL {
 sql: ${TABLE}.LANGUAGENULL;;
}
dimension: MASTERLABEL {
 sql: ${TABLE}.MASTERLABEL;;
}
dimension: CREATEDDATE {
 sql: ${TABLE}.CREATEDDATE;;
}
dimension: CREATEDBYID {
 sql: ${TABLE}.CREATEDBYID;;
}
dimension: LASTMODIFIEDDATE {
 sql: ${TABLE}.LASTMODIFIEDDATE;;
}
dimension: LASTMODIFIEDBYID {
 sql: ${TABLE}.LASTMODIFIEDBYID;;
}
dimension: SYSTEMMODSTAMP {
 sql: ${TABLE}.SYSTEMMODSTAMP;;
}
dimension: PERMISSIONSETLICENSEKEY {
 sql: ${TABLE}.PERMISSIONSETLICENSEKEY;;
}
measure: TOTALLICENSES {
type:count_distinct
 sql: ${TABLE}.TOTALLICENSES;;
}
dimension: STATUS {
 sql: ${TABLE}.STATUS;;
}
dimension: EXPIRATIONDATE {
 sql: ${TABLE}.EXPIRATIONDATE;;
}
dimension: MAXIMUMPERMISSIONSEMAILSINGLE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEMAILSINGLE;;
}
dimension: MAXIMUMPERMISSIONSEMAILMASS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEMAILMASS;;
}
dimension: MAXIMUMPERMISSIONSEDITTASK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITTASK;;
}
dimension: MAXIMUMPERMISSIONSEDITEVENT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITEVENT;;
}
dimension: MAXIMUMPERMISSIONSEXPORTREPORT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEXPORTREPORT;;
}
dimension: MAXIMUMPERMISSIONSIMPORTPERSONAL {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIMPORTPERSONAL;;
}
dimension: MAXIMUMPERMISSIONSDATAEXPORT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSDATAEXPORT;;
}
dimension: MAXIMUMPERMISSIONSMANAGEUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEUSERS;;
}
dimension: MAXIMUMPERMISSIONSEDITPUBLICFILTERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITPUBLICFILTERS;;
}
dimension: MAXIMUMPERMISSIONSEDITPUBLICTEMPLATES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITPUBLICTEMPLATES;;
}
dimension: MAXIMUMPERMISSIONSMODIFYALLDATA {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODIFYALLDATA;;
}
dimension: MAXIMUMPERMISSIONSMANAGECASES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECASES;;
}
dimension: MAXIMUMPERMISSIONSMASSINLINEEDIT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMASSINLINEEDIT;;
}
dimension: MAXIMUMPERMISSIONSEDITKNOWLEDGE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITKNOWLEDGE;;
}
dimension: MAXIMUMPERMISSIONSMANAGEKNOWLEDGE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEKNOWLEDGE;;
}
dimension: MAXIMUMPERMISSIONSMANAGESOLUTIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESOLUTIONS;;
}
dimension: MAXIMUMPERMISSIONSCUSTOMIZEAPPLICATION {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCUSTOMIZEAPPLICATION;;
}
dimension: MAXIMUMPERMISSIONSEDITREADONLYFIELDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITREADONLYFIELDS;;
}
dimension: MAXIMUMPERMISSIONSRUNREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSRUNREPORTS;;
}
dimension: MAXIMUMPERMISSIONSVIEWSETUP {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWSETUP;;
}
dimension: MAXIMUMPERMISSIONSTRANSFERANYENTITY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSTRANSFERANYENTITY;;
}
dimension: MAXIMUMPERMISSIONSNEWREPORTBUILDER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSNEWREPORTBUILDER;;
}
dimension: MAXIMUMPERMISSIONSACTIVATECONTRACT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSACTIVATECONTRACT;;
}
dimension: MAXIMUMPERMISSIONSACTIVATEORDER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSACTIVATEORDER;;
}
dimension: MAXIMUMPERMISSIONSIMPORTLEADS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIMPORTLEADS;;
}
dimension: MAXIMUMPERMISSIONSMANAGELEADS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGELEADS;;
}
dimension: MAXIMUMPERMISSIONSTRANSFERANYLEAD {
 sql: ${TABLE}.MAXIMUMPERMISSIONSTRANSFERANYLEAD;;
}
dimension: MAXIMUMPERMISSIONSVIEWALLDATA {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWALLDATA;;
}
dimension: MAXIMUMPERMISSIONSEDITPUBLICDOCUMENTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITPUBLICDOCUMENTS;;
}
dimension: MAXIMUMPERMISSIONSCONTENTHUBONPREMISEUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONTENTHUBONPREMISEUSER;;
}
dimension: MAXIMUMPERMISSIONSVIEWENCRYPTEDDATA {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWENCRYPTEDDATA;;
}
dimension: MAXIMUMPERMISSIONSEDITBRANDTEMPLATES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITBRANDTEMPLATES;;
}
dimension: MAXIMUMPERMISSIONSEDITHTMLTEMPLATES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITHTMLTEMPLATES;;
}
dimension: MAXIMUMPERMISSIONSCHATTERINTERNALUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTERINTERNALUSER;;
}
dimension: MAXIMUMPERMISSIONSMANAGEENCRYPTIONKEYS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEENCRYPTIONKEYS;;
}
dimension: MAXIMUMPERMISSIONSDELETEACTIVATEDCONTRACT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSDELETEACTIVATEDCONTRACT;;
}
dimension: MAXIMUMPERMISSIONSCHATTERINVITEEXTERNALUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTERINVITEEXTERNALUSERS;;
}
dimension: MAXIMUMPERMISSIONSSENDSITREQUESTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSENDSITREQUESTS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEREMOTEACCESS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEREMOTEACCESS;;
}
dimension: MAXIMUMPERMISSIONSCANUSENEWDASHBOARDBUILDER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANUSENEWDASHBOARDBUILDER;;
}
dimension: MAXIMUMPERMISSIONSMANAGECATEGORIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECATEGORIES;;
}
dimension: MAXIMUMPERMISSIONSCONVERTLEADS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONVERTLEADS;;
}
dimension: MAXIMUMPERMISSIONSPASSWORDNEVEREXPIRES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSPASSWORDNEVEREXPIRES;;
}
dimension: MAXIMUMPERMISSIONSUSETEAMREASSIGNWIZARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSUSETEAMREASSIGNWIZARDS;;
}
dimension: MAXIMUMPERMISSIONSEDITACTIVATEDORDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITACTIVATEDORDERS;;
}
dimension: MAXIMUMPERMISSIONSINSTALLPACKAGING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSTALLPACKAGING;;
}
dimension: MAXIMUMPERMISSIONSPUBLISHPACKAGING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSPUBLISHPACKAGING;;
}
dimension: MAXIMUMPERMISSIONSCHATTEROWNGROUPS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTEROWNGROUPS;;
}
dimension: MAXIMUMPERMISSIONSEDITOPPLINEITEMUNITPRICE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITOPPLINEITEMUNITPRICE;;
}
dimension: MAXIMUMPERMISSIONSCREATEPACKAGING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEPACKAGING;;
}
dimension: MAXIMUMPERMISSIONSBULKAPIHARDDELETE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSBULKAPIHARDDELETE;;
}
dimension: MAXIMUMPERMISSIONSSOLUTIONIMPORT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSOLUTIONIMPORT;;
}
dimension: MAXIMUMPERMISSIONSMANAGECALLCENTERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECALLCENTERS;;
}
dimension: MAXIMUMPERMISSIONSMANAGESYNONYMS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESYNONYMS;;
}
dimension: MAXIMUMPERMISSIONSVIEWCONTENT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWCONTENT;;
}
dimension: MAXIMUMPERMISSIONSMANAGEEMAILCLIENTCONFIG {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEEMAILCLIENTCONFIG;;
}
dimension: MAXIMUMPERMISSIONSENABLENOTIFICATIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSENABLENOTIFICATIONS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEDATAINTEGRATIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEDATAINTEGRATIONS;;
}
dimension: MAXIMUMPERMISSIONSDISTRIBUTEFROMPERSWKSP {
 sql: ${TABLE}.MAXIMUMPERMISSIONSDISTRIBUTEFROMPERSWKSP;;
}
dimension: MAXIMUMPERMISSIONSVIEWDATACATEGORIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWDATACATEGORIES;;
}
dimension: MAXIMUMPERMISSIONSMANAGEDATACATEGORIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEDATACATEGORIES;;
}
dimension: MAXIMUMPERMISSIONSAUTHORAPEX {
 sql: ${TABLE}.MAXIMUMPERMISSIONSAUTHORAPEX;;
}
dimension: MAXIMUMPERMISSIONSMANAGEMOBILE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEMOBILE;;
}
dimension: MAXIMUMPERMISSIONSAPIENABLED {
 sql: ${TABLE}.MAXIMUMPERMISSIONSAPIENABLED;;
}
dimension: MAXIMUMPERMISSIONSMANAGECUSTOMREPORTTYPES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECUSTOMREPORTTYPES;;
}
dimension: MAXIMUMPERMISSIONSEDITCASECOMMENTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITCASECOMMENTS;;
}
dimension: MAXIMUMPERMISSIONSTRANSFERANYCASE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSTRANSFERANYCASE;;
}
dimension: MAXIMUMPERMISSIONSCONTENTADMINISTRATOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONTENTADMINISTRATOR;;
}
dimension: MAXIMUMPERMISSIONSCREATEWORKSPACES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEWORKSPACES;;
}
dimension: MAXIMUMPERMISSIONSMANAGECONTENTPERMISSIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECONTENTPERMISSIONS;;
}
dimension: MAXIMUMPERMISSIONSMANAGECONTENTPROPERTIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECONTENTPROPERTIES;;
}
dimension: MAXIMUMPERMISSIONSMANAGECONTENTTYPES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECONTENTTYPES;;
}
dimension: MAXIMUMPERMISSIONSMANAGEEXCHANGECONFIG {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEEXCHANGECONFIG;;
}
dimension: MAXIMUMPERMISSIONSMANAGEANALYTICSNAPSHOTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEANALYTICSNAPSHOTS;;
}
dimension: MAXIMUMPERMISSIONSSCHEDULEREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSCHEDULEREPORTS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEBUSINESSHOURHOLIDAYS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEBUSINESSHOURHOLIDAYS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEDYNAMICDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEDYNAMICDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSCUSTOMSIDEBARONALLPAGES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCUSTOMSIDEBARONALLPAGES;;
}
dimension: MAXIMUMPERMISSIONSMANAGEINTERACTION {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEINTERACTION;;
}
dimension: MAXIMUMPERMISSIONSVIEWMYTEAMSDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWMYTEAMSDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSMODERATECHATTER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODERATECHATTER;;
}
dimension: MAXIMUMPERMISSIONSRESETPASSWORDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSRESETPASSWORDS;;
}
dimension: MAXIMUMPERMISSIONSFLOWUFLREQUIRED {
 sql: ${TABLE}.MAXIMUMPERMISSIONSFLOWUFLREQUIRED;;
}
dimension: MAXIMUMPERMISSIONSCANINSERTFEEDSYSTEMFIELDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANINSERTFEEDSYSTEMFIELDS;;
}
dimension: MAXIMUMPERMISSIONSACTIVITIESACCESS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSACTIVITIESACCESS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT;;
}
dimension: MAXIMUMPERMISSIONSEMAILTEMPLATEMANAGEMENT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEMAILTEMPLATEMANAGEMENT;;
}
dimension: MAXIMUMPERMISSIONSEMAILADMINISTRATION {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEMAILADMINISTRATION;;
}
dimension: MAXIMUMPERMISSIONSMANAGECHATTERMESSAGES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECHATTERMESSAGES;;
}
dimension: MAXIMUMPERMISSIONSALLOWEMAILIC {
 sql: ${TABLE}.MAXIMUMPERMISSIONSALLOWEMAILIC;;
}
dimension: MAXIMUMPERMISSIONSCHATTERFILELINK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTERFILELINK;;
}
dimension: MAXIMUMPERMISSIONSFORCETWOFACTOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSFORCETWOFACTOR;;
}
dimension: MAXIMUMPERMISSIONSVIEWEVENTLOGFILES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWEVENTLOGFILES;;
}
dimension: MAXIMUMPERMISSIONSMANAGENETWORKS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGENETWORKS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEAUTHPROVIDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEAUTHPROVIDERS;;
}
dimension: MAXIMUMPERMISSIONSRUNFLOW {
 sql: ${TABLE}.MAXIMUMPERMISSIONSRUNFLOW;;
}
dimension: MAXIMUMPERMISSIONSCREATECUSTOMIZEDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATECUSTOMIZEDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSCREATEDASHBOARDFOLDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEDASHBOARDFOLDERS;;
}
dimension: MAXIMUMPERMISSIONSVIEWPUBLICDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWPUBLICDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEDASHBDSINPUBFOLDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEDASHBDSINPUBFOLDERS;;
}
dimension: MAXIMUMPERMISSIONSCREATECUSTOMIZEREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATECUSTOMIZEREPORTS;;
}
dimension: MAXIMUMPERMISSIONSCREATEREPORTFOLDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEREPORTFOLDERS;;
}
dimension: MAXIMUMPERMISSIONSVIEWPUBLICREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWPUBLICREPORTS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEREPORTSINPUBFOLDERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEREPORTSINPUBFOLDERS;;
}
dimension: MAXIMUMPERMISSIONSEDITMYDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITMYDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSEDITMYREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITMYREPORTS;;
}
dimension: MAXIMUMPERMISSIONSVIEWALLUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWALLUSERS;;
}
dimension: MAXIMUMPERMISSIONSALLOWUNIVERSALSEARCH {
 sql: ${TABLE}.MAXIMUMPERMISSIONSALLOWUNIVERSALSEARCH;;
}
dimension: MAXIMUMPERMISSIONSCONNECTORGTOENVIRONMENTHUB {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONNECTORGTOENVIRONMENTHUB;;
}
dimension: MAXIMUMPERMISSIONSWORKCALIBRATIONUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSWORKCALIBRATIONUSER;;
}
dimension: MAXIMUMPERMISSIONSCREATECUSTOMIZEFILTERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATECUSTOMIZEFILTERS;;
}
dimension: MAXIMUMPERMISSIONSWORKDOTCOMUSERPERM {
 sql: ${TABLE}.MAXIMUMPERMISSIONSWORKDOTCOMUSERPERM;;
}
dimension: MAXIMUMPERMISSIONSCONTENTHUBUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONTENTHUBUSER;;
}
dimension: MAXIMUMPERMISSIONSGOVERNNETWORKS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSGOVERNNETWORKS;;
}
dimension: MAXIMUMPERMISSIONSSALESCONSOLE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSALESCONSOLE;;
}
dimension: MAXIMUMPERMISSIONSTWOFACTORAPI {
 sql: ${TABLE}.MAXIMUMPERMISSIONSTWOFACTORAPI;;
}
dimension: MAXIMUMPERMISSIONSDELETETOPICS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSDELETETOPICS;;
}
dimension: MAXIMUMPERMISSIONSEDITTOPICS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSEDITTOPICS;;
}
dimension: MAXIMUMPERMISSIONSCREATETOPICS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATETOPICS;;
}
dimension: MAXIMUMPERMISSIONSASSIGNTOPICS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSASSIGNTOPICS;;
}
dimension: MAXIMUMPERMISSIONSIDENTITYENABLED {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIDENTITYENABLED;;
}
dimension: MAXIMUMPERMISSIONSIDENTITYCONNECT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIDENTITYCONNECT;;
}
dimension: MAXIMUMPERMISSIONSALLOWVIEWKNOWLEDGE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSALLOWVIEWKNOWLEDGE;;
}
dimension: MAXIMUMPERMISSIONSCONTENTWORKSPACES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONTENTWORKSPACES;;
}
dimension: MAXIMUMPERMISSIONSMANAGESEARCHPROMOTIONRULES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESEARCHPROMOTIONRULES;;
}
dimension: MAXIMUMPERMISSIONSCUSTOMMOBILEAPPSACCESS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCUSTOMMOBILEAPPSACCESS;;
}
dimension: MAXIMUMPERMISSIONSVIEWHELPLINK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWHELPLINK;;
}
dimension: MAXIMUMPERMISSIONSMANAGEPROFILESPERMISSIONSETS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEPROFILESPERMISSIONSETS;;
}
dimension: MAXIMUMPERMISSIONSASSIGNPERMISSIONSETS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSASSIGNPERMISSIONSETS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEROLES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEROLES;;
}
dimension: MAXIMUMPERMISSIONSMANAGEIPADDRESSES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEIPADDRESSES;;
}
dimension: MAXIMUMPERMISSIONSMANAGESHARING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESHARING;;
}
dimension: MAXIMUMPERMISSIONSMANAGEINTERNALUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEINTERNALUSERS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEPASSWORDPOLICIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEPASSWORDPOLICIES;;
}
dimension: MAXIMUMPERMISSIONSMANAGELOGINACCESSPOLICIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGELOGINACCESSPOLICIES;;
}
dimension: MAXIMUMPERMISSIONSVIEWPLATFORMEVENTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWPLATFORMEVENTS;;
}
dimension: MAXIMUMPERMISSIONSMANAGECUSTOMPERMISSIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECUSTOMPERMISSIONS;;
}
dimension: MAXIMUMPERMISSIONSCANVERIFYCOMMENT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANVERIFYCOMMENT;;
}
dimension: MAXIMUMPERMISSIONSMANAGEUNLISTEDGROUPS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEUNLISTEDGROUPS;;
}
dimension: MAXIMUMPERMISSIONSSTDAUTOMATICACTIVITYCAPTURE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSTDAUTOMATICACTIVITYCAPTURE;;
}
dimension: MAXIMUMPERMISSIONSMODIFYSECUREAGENTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODIFYSECUREAGENTS;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSAPPDASHBOARDEDITOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSAPPDASHBOARDEDITOR;;
}
dimension: MAXIMUMPERMISSIONSMANAGETWOFACTOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGETWOFACTOR;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSAPPUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSAPPUSER;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSAPPADMIN {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSAPPADMIN;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSAPPELTEDITOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSAPPELTEDITOR;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSAPPUPLOADUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSAPPUPLOADUSER;;
}
dimension: MAXIMUMPERMISSIONSINSIGHTSCREATEAPPLICATION {
 sql: ${TABLE}.MAXIMUMPERMISSIONSINSIGHTSCREATEAPPLICATION;;
}
dimension: MAXIMUMPERMISSIONSLIGHTNINGEXPERIENCEUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSLIGHTNINGEXPERIENCEUSER;;
}
dimension: MAXIMUMPERMISSIONSVIEWDATALEAKAGEEVENTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWDATALEAKAGEEVENTS;;
}
dimension: MAXIMUMPERMISSIONSCONFIGCUSTOMRECS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCONFIGCUSTOMRECS;;
}
dimension: MAXIMUMPERMISSIONSSUBMITMACROSALLOWED {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBMITMACROSALLOWED;;
}
dimension: MAXIMUMPERMISSIONSBULKMACROSALLOWED {
 sql: ${TABLE}.MAXIMUMPERMISSIONSBULKMACROSALLOWED;;
}
dimension: MAXIMUMPERMISSIONSSHAREINTERNALARTICLES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSHAREINTERNALARTICLES;;
}
dimension: MAXIMUMPERMISSIONSMANAGESESSIONPERMISSIONSETS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESESSIONPERMISSIONSETS;;
}
dimension: MAXIMUMPERMISSIONSMANAGETEMPLATEDAPP {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGETEMPLATEDAPP;;
}
dimension: MAXIMUMPERMISSIONSUSETEMPLATEDAPP {
 sql: ${TABLE}.MAXIMUMPERMISSIONSUSETEMPLATEDAPP;;
}
dimension: MAXIMUMPERMISSIONSSENDANNOUNCEMENTEMAILS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSENDANNOUNCEMENTEMAILS;;
}
dimension: MAXIMUMPERMISSIONSCHATTEREDITOWNPOST {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTEREDITOWNPOST;;
}
dimension: MAXIMUMPERMISSIONSCHATTEREDITOWNRECORDPOST {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTEREDITOWNRECORDPOST;;
}
dimension: MAXIMUMPERMISSIONSSALESANALYTICSUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSALESANALYTICSUSER;;
}
dimension: MAXIMUMPERMISSIONSADMINANALYTICSUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSADMINANALYTICSUSER;;
}
dimension: MAXIMUMPERMISSIONSSERVICEANALYTICSUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSERVICEANALYTICSUSER;;
}
dimension: MAXIMUMPERMISSIONSCREATEAUDITFIELDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEAUDITFIELDS;;
}
dimension: MAXIMUMPERMISSIONSUPDATEWITHINACTIVEOWNER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSUPDATEWITHINACTIVEOWNER;;
}
dimension: MAXIMUMPERMISSIONSWAVETABULARDOWNLOAD {
 sql: ${TABLE}.MAXIMUMPERMISSIONSWAVETABULARDOWNLOAD;;
}
dimension: MAXIMUMPERMISSIONSAUTOMATICACTIVITYCAPTURE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSAUTOMATICACTIVITYCAPTURE;;
}
dimension: MAXIMUMPERMISSIONSIMPORTCUSTOMOBJECTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIMPORTCUSTOMOBJECTS;;
}
dimension: MAXIMUMPERMISSIONSDELEGATEDTWOFACTOR {
 sql: ${TABLE}.MAXIMUMPERMISSIONSDELEGATEDTWOFACTOR;;
}
dimension: MAXIMUMPERMISSIONSCHATTERCOMPOSEUICODESNIPPET {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHATTERCOMPOSEUICODESNIPPET;;
}
dimension: MAXIMUMPERMISSIONSSELECTFILESFROMSALESFORCE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSELECTFILESFROMSALESFORCE;;
}
dimension: MAXIMUMPERMISSIONSMODERATENETWORKUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODERATENETWORKUSERS;;
}
dimension: MAXIMUMPERMISSIONSMERGETOPICS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMERGETOPICS;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS;;
}
dimension: MAXIMUMPERMISSIONSMANAGEPVTRPTSANDDASHBDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEPVTRPTSANDDASHBDS;;
}
dimension: MAXIMUMPERMISSIONSALLOWLIGHTNINGLOGIN {
 sql: ${TABLE}.MAXIMUMPERMISSIONSALLOWLIGHTNINGLOGIN;;
}
dimension: MAXIMUMPERMISSIONSCAMPAIGNINFLUENCE2 {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCAMPAIGNINFLUENCE2;;
}
dimension: MAXIMUMPERMISSIONSVIEWDATAASSESSMENT {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWDATAASSESSMENT;;
}
dimension: MAXIMUMPERMISSIONSREMOVEDIRECTMESSAGEMEMBERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSREMOVEDIRECTMESSAGEMEMBERS;;
}
dimension: MAXIMUMPERMISSIONSCANAPPROVEFEEDPOST {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANAPPROVEFEEDPOST;;
}
dimension: MAXIMUMPERMISSIONSADDDIRECTMESSAGEMEMBERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSADDDIRECTMESSAGEMEMBERS;;
}
dimension: MAXIMUMPERMISSIONSALLOWVIEWEDITCONVERTEDLEADS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSALLOWVIEWEDITCONVERTEDLEADS;;
}
dimension: MAXIMUMPERMISSIONSSHOWCOMPANYNAMEASUSERBADGE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSHOWCOMPANYNAMEASUSERBADGE;;
}
dimension: MAXIMUMPERMISSIONSACCESSCMC {
 sql: ${TABLE}.MAXIMUMPERMISSIONSACCESSCMC;;
}
dimension: MAXIMUMPERMISSIONSVIEWHEALTHCHECK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWHEALTHCHECK;;
}
dimension: MAXIMUMPERMISSIONSMANAGEHEALTHCHECK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEHEALTHCHECK;;
}
dimension: MAXIMUMPERMISSIONSPACKAGING2 {
 sql: ${TABLE}.MAXIMUMPERMISSIONSPACKAGING2;;
}
dimension: MAXIMUMPERMISSIONSMANAGECERTIFICATES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGECERTIFICATES;;
}
dimension: MAXIMUMPERMISSIONSCREATEREPORTINLIGHTNING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEREPORTINLIGHTNING;;
}
dimension: MAXIMUMPERMISSIONSPREVENTCLASSICEXPERIENCE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSPREVENTCLASSICEXPERIENCE;;
}
dimension: MAXIMUMPERMISSIONSHIDEREADBYLIST {
 sql: ${TABLE}.MAXIMUMPERMISSIONSHIDEREADBYLIST;;
}
dimension: MAXIMUMPERMISSIONSUSESMARTDATADISCOVERY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSUSESMARTDATADISCOVERY;;
}
dimension: MAXIMUMPERMISSIONSGETSMARTDATADISCOVERY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSGETSMARTDATADISCOVERY;;
}
dimension: MAXIMUMPERMISSIONSCREATEUPDATESDDDATASET {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEUPDATESDDDATASET;;
}
dimension: MAXIMUMPERMISSIONSCREATEUPDATESDDSTORY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATEUPDATESDDSTORY;;
}
dimension: MAXIMUMPERMISSIONSMANAGESMARTDATADISCOVERY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESMARTDATADISCOVERY;;
}
dimension: MAXIMUMPERMISSIONSSHARESMARTDATADISCOVERYSTORY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSHARESMARTDATADISCOVERYSTORY;;
}
dimension: MAXIMUMPERMISSIONSMANAGESMARTDATADISCOVERYMODEL {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESMARTDATADISCOVERYMODEL;;
}
dimension: MAXIMUMPERMISSIONSLISTEMAILSEND {
 sql: ${TABLE}.MAXIMUMPERMISSIONSLISTEMAILSEND;;
}
dimension: MAXIMUMPERMISSIONSFEEDPINNING {
 sql: ${TABLE}.MAXIMUMPERMISSIONSFEEDPINNING;;
}
dimension: MAXIMUMPERMISSIONSCHANGEDASHBOARDCOLORS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCHANGEDASHBOARDCOLORS;;
}
dimension: MAXIMUMPERMISSIONSIOTUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSIOTUSER;;
}
dimension: MAXIMUMPERMISSIONSMANAGERECOMMENDATIONSTRATEGIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGERECOMMENDATIONSTRATEGIES;;
}
dimension: MAXIMUMPERMISSIONSMANAGEPROPOSITIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGEPROPOSITIONS;;
}
dimension: MAXIMUMPERMISSIONSCLOSECONVERSATIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCLOSECONVERSATIONS;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBEREPORTROLESGRPS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBEREPORTROLESGRPS;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBEDASHBOARDROLESGRPS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBEDASHBOARDROLESGRPS;;
}
dimension: MAXIMUMPERMISSIONSUSEWEBLINK {
 sql: ${TABLE}.MAXIMUMPERMISSIONSUSEWEBLINK;;
}
dimension: MAXIMUMPERMISSIONSHASUNLIMITEDNBAEXECUTIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSHASUNLIMITEDNBAEXECUTIONS;;
}
dimension: MAXIMUMPERMISSIONSVIEWONLYEMBEDDEDAPPUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWONLYEMBEDDEDAPPUSER;;
}
dimension: MAXIMUMPERMISSIONSVIEWALLACTIVITIES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWALLACTIVITIES;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS;;
}
dimension: MAXIMUMPERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBEREPORTSRUNASUSER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBEREPORTSRUNASUSER;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS;;
}
dimension: MAXIMUMPERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS;;
}
dimension: MAXIMUMPERMISSIONSCREATELTNGTEMPINPUB {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATELTNGTEMPINPUB;;
}
dimension: MAXIMUMPERMISSIONSTRANSACTIONALEMAILSEND {
 sql: ${TABLE}.MAXIMUMPERMISSIONSTRANSACTIONALEMAILSEND;;
}
dimension: MAXIMUMPERMISSIONSCREATELTNGTEMPFOLDER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCREATELTNGTEMPFOLDER;;
}
dimension: MAXIMUMPERMISSIONSAPEXRESTSERVICES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSAPEXRESTSERVICES;;
}
dimension: MAXIMUMPERMISSIONSENABLECOMMUNITYAPPLAUNCHER {
 sql: ${TABLE}.MAXIMUMPERMISSIONSENABLECOMMUNITYAPPLAUNCHER;;
}
dimension: MAXIMUMPERMISSIONSGIVERECOGNITIONBADGE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSGIVERECOGNITIONBADGE;;
}
dimension: MAXIMUMPERMISSIONSLTNGPROMORESERVED01USERPERM {
 sql: ${TABLE}.MAXIMUMPERMISSIONSLTNGPROMORESERVED01USERPERM;;
}
dimension: MAXIMUMPERMISSIONSCANEDITDATAPREPRECIPE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANEDITDATAPREPRECIPE;;
}
dimension: MAXIMUMPERMISSIONSADDANALYTICSREMOTECONNECTIONS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSADDANALYTICSREMOTECONNECTIONS;;
}
dimension: MAXIMUMPERMISSIONSMANAGESURVEYS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMANAGESURVEYS;;
}
dimension: MAXIMUMPERMISSIONSRECORDVISIBILITYAPI {
 sql: ${TABLE}.MAXIMUMPERMISSIONSRECORDVISIBILITYAPI;;
}
dimension: MAXIMUMPERMISSIONSVIEWROLES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSVIEWROLES;;
}
dimension: MAXIMUMPERMISSIONSSMARTDATADISCOVERYFORCOMMUNITY {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSMARTDATADISCOVERYFORCOMMUNITY;;
}
dimension: MAXIMUMPERMISSIONSCANMANAGEMAPS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSCANMANAGEMAPS;;
}
dimension: MAXIMUMPERMISSIONSSTORYONDSWITHPREDICATE {
 sql: ${TABLE}.MAXIMUMPERMISSIONSSTORYONDSWITHPREDICATE;;
}
dimension: MAXIMUMPERMISSIONSMODIFYDATACLASSIFICATION {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODIFYDATACLASSIFICATION;;
}
dimension: MAXIMUMPERMISSIONSPRIVACYDATAACCESS {
 sql: ${TABLE}.MAXIMUMPERMISSIONSPRIVACYDATAACCESS;;
}
dimension: MAXIMUMPERMISSIONSQUERYALLFILES {
 sql: ${TABLE}.MAXIMUMPERMISSIONSQUERYALLFILES;;
}
dimension: MAXIMUMPERMISSIONSMODIFYMETADATA {
 sql: ${TABLE}.MAXIMUMPERMISSIONSMODIFYMETADATA;;
}
measure: USEDLICENSES {
type:count_distinct
 sql: ${TABLE}.USEDLICENSES;;
}
}


view: PROFILE__e99f63c3_ea19_46a8_8f3d_aba09d087ce9 {
sql_table_name:sforce.SFORCE.PROFILE ;;
dimension: ID {
 sql: ${TABLE}.ID;;
}
dimension: NAME {
 sql: ${TABLE}.NAME;;
}
dimension: PERMISSIONSEMAILSINGLE {
 sql: ${TABLE}.PERMISSIONSEMAILSINGLE;;
}
dimension: PERMISSIONSEMAILMASS {
 sql: ${TABLE}.PERMISSIONSEMAILMASS;;
}
dimension: PERMISSIONSEDITTASK {
 sql: ${TABLE}.PERMISSIONSEDITTASK;;
}
dimension: PERMISSIONSEDITEVENT {
 sql: ${TABLE}.PERMISSIONSEDITEVENT;;
}
dimension: PERMISSIONSEXPORTREPORT {
 sql: ${TABLE}.PERMISSIONSEXPORTREPORT;;
}
dimension: PERMISSIONSIMPORTPERSONAL {
 sql: ${TABLE}.PERMISSIONSIMPORTPERSONAL;;
}
dimension: PERMISSIONSDATAEXPORT {
 sql: ${TABLE}.PERMISSIONSDATAEXPORT;;
}
dimension: PERMISSIONSMANAGEUSERS {
 sql: ${TABLE}.PERMISSIONSMANAGEUSERS;;
}
dimension: PERMISSIONSEDITPUBLICFILTERS {
 sql: ${TABLE}.PERMISSIONSEDITPUBLICFILTERS;;
}
dimension: PERMISSIONSEDITPUBLICTEMPLATES {
 sql: ${TABLE}.PERMISSIONSEDITPUBLICTEMPLATES;;
}
dimension: PERMISSIONSMODIFYALLDATA {
 sql: ${TABLE}.PERMISSIONSMODIFYALLDATA;;
}
dimension: PERMISSIONSMANAGECASES {
 sql: ${TABLE}.PERMISSIONSMANAGECASES;;
}
dimension: PERMISSIONSMASSINLINEEDIT {
 sql: ${TABLE}.PERMISSIONSMASSINLINEEDIT;;
}
dimension: PERMISSIONSEDITKNOWLEDGE {
 sql: ${TABLE}.PERMISSIONSEDITKNOWLEDGE;;
}
dimension: PERMISSIONSMANAGEKNOWLEDGE {
 sql: ${TABLE}.PERMISSIONSMANAGEKNOWLEDGE;;
}
dimension: PERMISSIONSMANAGESOLUTIONS {
 sql: ${TABLE}.PERMISSIONSMANAGESOLUTIONS;;
}
dimension: PERMISSIONSCUSTOMIZEAPPLICATION {
 sql: ${TABLE}.PERMISSIONSCUSTOMIZEAPPLICATION;;
}
dimension: PERMISSIONSEDITREADONLYFIELDS {
 sql: ${TABLE}.PERMISSIONSEDITREADONLYFIELDS;;
}
dimension: PERMISSIONSRUNREPORTS {
 sql: ${TABLE}.PERMISSIONSRUNREPORTS;;
}
dimension: PERMISSIONSVIEWSETUP {
 sql: ${TABLE}.PERMISSIONSVIEWSETUP;;
}
dimension: PERMISSIONSTRANSFERANYENTITY {
 sql: ${TABLE}.PERMISSIONSTRANSFERANYENTITY;;
}
dimension: PERMISSIONSNEWREPORTBUILDER {
 sql: ${TABLE}.PERMISSIONSNEWREPORTBUILDER;;
}
dimension: PERMISSIONSACTIVATECONTRACT {
 sql: ${TABLE}.PERMISSIONSACTIVATECONTRACT;;
}
dimension: PERMISSIONSACTIVATEORDER {
 sql: ${TABLE}.PERMISSIONSACTIVATEORDER;;
}
dimension: PERMISSIONSIMPORTLEADS {
 sql: ${TABLE}.PERMISSIONSIMPORTLEADS;;
}
dimension: PERMISSIONSMANAGELEADS {
 sql: ${TABLE}.PERMISSIONSMANAGELEADS;;
}
dimension: PERMISSIONSTRANSFERANYLEAD {
 sql: ${TABLE}.PERMISSIONSTRANSFERANYLEAD;;
}
dimension: PERMISSIONSVIEWALLDATA {
 sql: ${TABLE}.PERMISSIONSVIEWALLDATA;;
}
dimension: PERMISSIONSEDITPUBLICDOCUMENTS {
 sql: ${TABLE}.PERMISSIONSEDITPUBLICDOCUMENTS;;
}
dimension: PERMISSIONSCONTENTHUBONPREMISEUSER {
 sql: ${TABLE}.PERMISSIONSCONTENTHUBONPREMISEUSER;;
}
dimension: PERMISSIONSVIEWENCRYPTEDDATA {
 sql: ${TABLE}.PERMISSIONSVIEWENCRYPTEDDATA;;
}
dimension: PERMISSIONSEDITBRANDTEMPLATES {
 sql: ${TABLE}.PERMISSIONSEDITBRANDTEMPLATES;;
}
dimension: PERMISSIONSEDITHTMLTEMPLATES {
 sql: ${TABLE}.PERMISSIONSEDITHTMLTEMPLATES;;
}
dimension: PERMISSIONSCHATTERINTERNALUSER {
 sql: ${TABLE}.PERMISSIONSCHATTERINTERNALUSER;;
}
dimension: PERMISSIONSMANAGEENCRYPTIONKEYS {
 sql: ${TABLE}.PERMISSIONSMANAGEENCRYPTIONKEYS;;
}
dimension: PERMISSIONSDELETEACTIVATEDCONTRACT {
 sql: ${TABLE}.PERMISSIONSDELETEACTIVATEDCONTRACT;;
}
dimension: PERMISSIONSCHATTERINVITEEXTERNALUSERS {
 sql: ${TABLE}.PERMISSIONSCHATTERINVITEEXTERNALUSERS;;
}
dimension: PERMISSIONSSENDSITREQUESTS {
 sql: ${TABLE}.PERMISSIONSSENDSITREQUESTS;;
}
dimension: PERMISSIONSMANAGEREMOTEACCESS {
 sql: ${TABLE}.PERMISSIONSMANAGEREMOTEACCESS;;
}
dimension: PERMISSIONSCANUSENEWDASHBOARDBUILDER {
 sql: ${TABLE}.PERMISSIONSCANUSENEWDASHBOARDBUILDER;;
}
dimension: PERMISSIONSMANAGECATEGORIES {
 sql: ${TABLE}.PERMISSIONSMANAGECATEGORIES;;
}
dimension: PERMISSIONSCONVERTLEADS {
 sql: ${TABLE}.PERMISSIONSCONVERTLEADS;;
}
dimension: PERMISSIONSPASSWORDNEVEREXPIRES {
 sql: ${TABLE}.PERMISSIONSPASSWORDNEVEREXPIRES;;
}
dimension: PERMISSIONSUSETEAMREASSIGNWIZARDS {
 sql: ${TABLE}.PERMISSIONSUSETEAMREASSIGNWIZARDS;;
}
dimension: PERMISSIONSEDITACTIVATEDORDERS {
 sql: ${TABLE}.PERMISSIONSEDITACTIVATEDORDERS;;
}
dimension: PERMISSIONSINSTALLMULTIFORCE {
 sql: ${TABLE}.PERMISSIONSINSTALLMULTIFORCE;;
}
dimension: PERMISSIONSPUBLISHMULTIFORCE {
 sql: ${TABLE}.PERMISSIONSPUBLISHMULTIFORCE;;
}
dimension: PERMISSIONSCHATTEROWNGROUPS {
 sql: ${TABLE}.PERMISSIONSCHATTEROWNGROUPS;;
}
dimension: PERMISSIONSEDITOPPLINEITEMUNITPRICE {
 sql: ${TABLE}.PERMISSIONSEDITOPPLINEITEMUNITPRICE;;
}
dimension: PERMISSIONSCREATEMULTIFORCE {
 sql: ${TABLE}.PERMISSIONSCREATEMULTIFORCE;;
}
dimension: PERMISSIONSBULKAPIHARDDELETE {
 sql: ${TABLE}.PERMISSIONSBULKAPIHARDDELETE;;
}
dimension: PERMISSIONSSOLUTIONIMPORT {
 sql: ${TABLE}.PERMISSIONSSOLUTIONIMPORT;;
}
dimension: PERMISSIONSMANAGECALLCENTERS {
 sql: ${TABLE}.PERMISSIONSMANAGECALLCENTERS;;
}
dimension: PERMISSIONSMANAGESYNONYMS {
 sql: ${TABLE}.PERMISSIONSMANAGESYNONYMS;;
}
dimension: PERMISSIONSVIEWCONTENT {
 sql: ${TABLE}.PERMISSIONSVIEWCONTENT;;
}
dimension: PERMISSIONSMANAGEEMAILCLIENTCONFIG {
 sql: ${TABLE}.PERMISSIONSMANAGEEMAILCLIENTCONFIG;;
}
dimension: PERMISSIONSENABLENOTIFICATIONS {
 sql: ${TABLE}.PERMISSIONSENABLENOTIFICATIONS;;
}
dimension: PERMISSIONSMANAGEDATAINTEGRATIONS {
 sql: ${TABLE}.PERMISSIONSMANAGEDATAINTEGRATIONS;;
}
dimension: PERMISSIONSDISTRIBUTEFROMPERSWKSP {
 sql: ${TABLE}.PERMISSIONSDISTRIBUTEFROMPERSWKSP;;
}
dimension: PERMISSIONSVIEWDATACATEGORIES {
 sql: ${TABLE}.PERMISSIONSVIEWDATACATEGORIES;;
}
dimension: PERMISSIONSMANAGEDATACATEGORIES {
 sql: ${TABLE}.PERMISSIONSMANAGEDATACATEGORIES;;
}
dimension: PERMISSIONSAUTHORAPEX {
 sql: ${TABLE}.PERMISSIONSAUTHORAPEX;;
}
dimension: PERMISSIONSMANAGEMOBILE {
 sql: ${TABLE}.PERMISSIONSMANAGEMOBILE;;
}
dimension: PERMISSIONSAPIENABLED {
 sql: ${TABLE}.PERMISSIONSAPIENABLED;;
}
dimension: PERMISSIONSMANAGECUSTOMREPORTTYPES {
 sql: ${TABLE}.PERMISSIONSMANAGECUSTOMREPORTTYPES;;
}
dimension: PERMISSIONSEDITCASECOMMENTS {
 sql: ${TABLE}.PERMISSIONSEDITCASECOMMENTS;;
}
dimension: PERMISSIONSTRANSFERANYCASE {
 sql: ${TABLE}.PERMISSIONSTRANSFERANYCASE;;
}
dimension: PERMISSIONSCONTENTADMINISTRATOR {
 sql: ${TABLE}.PERMISSIONSCONTENTADMINISTRATOR;;
}
dimension: PERMISSIONSCREATEWORKSPACES {
 sql: ${TABLE}.PERMISSIONSCREATEWORKSPACES;;
}
dimension: PERMISSIONSMANAGECONTENTPERMISSIONS {
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTPERMISSIONS;;
}
dimension: PERMISSIONSMANAGECONTENTPROPERTIES {
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTPROPERTIES;;
}
dimension: PERMISSIONSMANAGECONTENTTYPES {
 sql: ${TABLE}.PERMISSIONSMANAGECONTENTTYPES;;
}
dimension: PERMISSIONSMANAGEEXCHANGECONFIG {
 sql: ${TABLE}.PERMISSIONSMANAGEEXCHANGECONFIG;;
}
dimension: PERMISSIONSMANAGEANALYTICSNAPSHOTS {
 sql: ${TABLE}.PERMISSIONSMANAGEANALYTICSNAPSHOTS;;
}
dimension: PERMISSIONSSCHEDULEREPORTS {
 sql: ${TABLE}.PERMISSIONSSCHEDULEREPORTS;;
}
dimension: PERMISSIONSMANAGEBUSINESSHOURHOLIDAYS {
 sql: ${TABLE}.PERMISSIONSMANAGEBUSINESSHOURHOLIDAYS;;
}
dimension: PERMISSIONSMANAGEDYNAMICDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSMANAGEDYNAMICDASHBOARDS;;
}
dimension: PERMISSIONSCUSTOMSIDEBARONALLPAGES {
 sql: ${TABLE}.PERMISSIONSCUSTOMSIDEBARONALLPAGES;;
}
dimension: PERMISSIONSMANAGEINTERACTION {
 sql: ${TABLE}.PERMISSIONSMANAGEINTERACTION;;
}
dimension: PERMISSIONSVIEWMYTEAMSDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSVIEWMYTEAMSDASHBOARDS;;
}
dimension: PERMISSIONSMODERATECHATTER {
 sql: ${TABLE}.PERMISSIONSMODERATECHATTER;;
}
dimension: PERMISSIONSRESETPASSWORDS {
 sql: ${TABLE}.PERMISSIONSRESETPASSWORDS;;
}
dimension: PERMISSIONSFLOWUFLREQUIRED {
 sql: ${TABLE}.PERMISSIONSFLOWUFLREQUIRED;;
}
dimension: PERMISSIONSCANINSERTFEEDSYSTEMFIELDS {
 sql: ${TABLE}.PERMISSIONSCANINSERTFEEDSYSTEMFIELDS;;
}
dimension: PERMISSIONSACTIVITIESACCESS {
 sql: ${TABLE}.PERMISSIONSACTIVITIESACCESS;;
}
dimension: PERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT {
 sql: ${TABLE}.PERMISSIONSMANAGEKNOWLEDGEIMPORTEXPORT;;
}
dimension: PERMISSIONSEMAILTEMPLATEMANAGEMENT {
 sql: ${TABLE}.PERMISSIONSEMAILTEMPLATEMANAGEMENT;;
}
dimension: PERMISSIONSEMAILADMINISTRATION {
 sql: ${TABLE}.PERMISSIONSEMAILADMINISTRATION;;
}
dimension: PERMISSIONSMANAGECHATTERMESSAGES {
 sql: ${TABLE}.PERMISSIONSMANAGECHATTERMESSAGES;;
}
dimension: PERMISSIONSALLOWEMAILIC {
 sql: ${TABLE}.PERMISSIONSALLOWEMAILIC;;
}
dimension: PERMISSIONSCHATTERFILELINK {
 sql: ${TABLE}.PERMISSIONSCHATTERFILELINK;;
}
dimension: PERMISSIONSFORCETWOFACTOR {
 sql: ${TABLE}.PERMISSIONSFORCETWOFACTOR;;
}
dimension: PERMISSIONSVIEWEVENTLOGFILES {
 sql: ${TABLE}.PERMISSIONSVIEWEVENTLOGFILES;;
}
dimension: PERMISSIONSMANAGENETWORKS {
 sql: ${TABLE}.PERMISSIONSMANAGENETWORKS;;
}
dimension: PERMISSIONSMANAGEAUTHPROVIDERS {
 sql: ${TABLE}.PERMISSIONSMANAGEAUTHPROVIDERS;;
}
dimension: PERMISSIONSRUNFLOW {
 sql: ${TABLE}.PERMISSIONSRUNFLOW;;
}
dimension: PERMISSIONSCREATECUSTOMIZEDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEDASHBOARDS;;
}
dimension: PERMISSIONSCREATEDASHBOARDFOLDERS {
 sql: ${TABLE}.PERMISSIONSCREATEDASHBOARDFOLDERS;;
}
dimension: PERMISSIONSVIEWPUBLICDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSVIEWPUBLICDASHBOARDS;;
}
dimension: PERMISSIONSMANAGEDASHBDSINPUBFOLDERS {
 sql: ${TABLE}.PERMISSIONSMANAGEDASHBDSINPUBFOLDERS;;
}
dimension: PERMISSIONSCREATECUSTOMIZEREPORTS {
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEREPORTS;;
}
dimension: PERMISSIONSCREATEREPORTFOLDERS {
 sql: ${TABLE}.PERMISSIONSCREATEREPORTFOLDERS;;
}
dimension: PERMISSIONSVIEWPUBLICREPORTS {
 sql: ${TABLE}.PERMISSIONSVIEWPUBLICREPORTS;;
}
dimension: PERMISSIONSMANAGEREPORTSINPUBFOLDERS {
 sql: ${TABLE}.PERMISSIONSMANAGEREPORTSINPUBFOLDERS;;
}
dimension: PERMISSIONSEDITMYDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSEDITMYDASHBOARDS;;
}
dimension: PERMISSIONSEDITMYREPORTS {
 sql: ${TABLE}.PERMISSIONSEDITMYREPORTS;;
}
dimension: PERMISSIONSVIEWALLUSERS {
 sql: ${TABLE}.PERMISSIONSVIEWALLUSERS;;
}
dimension: PERMISSIONSALLOWUNIVERSALSEARCH {
 sql: ${TABLE}.PERMISSIONSALLOWUNIVERSALSEARCH;;
}
dimension: PERMISSIONSCONNECTORGTOENVIRONMENTHUB {
 sql: ${TABLE}.PERMISSIONSCONNECTORGTOENVIRONMENTHUB;;
}
dimension: PERMISSIONSWORKCALIBRATIONUSER {
 sql: ${TABLE}.PERMISSIONSWORKCALIBRATIONUSER;;
}
dimension: PERMISSIONSCREATECUSTOMIZEFILTERS {
 sql: ${TABLE}.PERMISSIONSCREATECUSTOMIZEFILTERS;;
}
dimension: PERMISSIONSWORKDOTCOMUSERPERM {
 sql: ${TABLE}.PERMISSIONSWORKDOTCOMUSERPERM;;
}
dimension: PERMISSIONSCONTENTHUBUSER {
 sql: ${TABLE}.PERMISSIONSCONTENTHUBUSER;;
}
dimension: PERMISSIONSGOVERNNETWORKS {
 sql: ${TABLE}.PERMISSIONSGOVERNNETWORKS;;
}
dimension: PERMISSIONSSALESCONSOLE {
 sql: ${TABLE}.PERMISSIONSSALESCONSOLE;;
}
dimension: PERMISSIONSTWOFACTORAPI {
 sql: ${TABLE}.PERMISSIONSTWOFACTORAPI;;
}
dimension: PERMISSIONSDELETETOPICS {
 sql: ${TABLE}.PERMISSIONSDELETETOPICS;;
}
dimension: PERMISSIONSEDITTOPICS {
 sql: ${TABLE}.PERMISSIONSEDITTOPICS;;
}
dimension: PERMISSIONSCREATETOPICS {
 sql: ${TABLE}.PERMISSIONSCREATETOPICS;;
}
dimension: PERMISSIONSASSIGNTOPICS {
 sql: ${TABLE}.PERMISSIONSASSIGNTOPICS;;
}
dimension: PERMISSIONSIDENTITYENABLED {
 sql: ${TABLE}.PERMISSIONSIDENTITYENABLED;;
}
dimension: PERMISSIONSIDENTITYCONNECT {
 sql: ${TABLE}.PERMISSIONSIDENTITYCONNECT;;
}
dimension: PERMISSIONSALLOWVIEWKNOWLEDGE {
 sql: ${TABLE}.PERMISSIONSALLOWVIEWKNOWLEDGE;;
}
dimension: PERMISSIONSCONTENTWORKSPACES {
 sql: ${TABLE}.PERMISSIONSCONTENTWORKSPACES;;
}
dimension: PERMISSIONSMANAGESEARCHPROMOTIONRULES {
 sql: ${TABLE}.PERMISSIONSMANAGESEARCHPROMOTIONRULES;;
}
dimension: PERMISSIONSCUSTOMMOBILEAPPSACCESS {
 sql: ${TABLE}.PERMISSIONSCUSTOMMOBILEAPPSACCESS;;
}
dimension: PERMISSIONSVIEWHELPLINK {
 sql: ${TABLE}.PERMISSIONSVIEWHELPLINK;;
}
dimension: PERMISSIONSMANAGEPROFILESPERMISSIONSETS {
 sql: ${TABLE}.PERMISSIONSMANAGEPROFILESPERMISSIONSETS;;
}
dimension: PERMISSIONSASSIGNPERMISSIONSETS {
 sql: ${TABLE}.PERMISSIONSASSIGNPERMISSIONSETS;;
}
dimension: PERMISSIONSMANAGEROLES {
 sql: ${TABLE}.PERMISSIONSMANAGEROLES;;
}
dimension: PERMISSIONSMANAGEIPADDRESSES {
 sql: ${TABLE}.PERMISSIONSMANAGEIPADDRESSES;;
}
dimension: PERMISSIONSMANAGESHARING {
 sql: ${TABLE}.PERMISSIONSMANAGESHARING;;
}
dimension: PERMISSIONSMANAGEINTERNALUSERS {
 sql: ${TABLE}.PERMISSIONSMANAGEINTERNALUSERS;;
}
dimension: PERMISSIONSMANAGEPASSWORDPOLICIES {
 sql: ${TABLE}.PERMISSIONSMANAGEPASSWORDPOLICIES;;
}
dimension: PERMISSIONSMANAGELOGINACCESSPOLICIES {
 sql: ${TABLE}.PERMISSIONSMANAGELOGINACCESSPOLICIES;;
}
dimension: PERMISSIONSVIEWPLATFORMEVENTS {
 sql: ${TABLE}.PERMISSIONSVIEWPLATFORMEVENTS;;
}
dimension: PERMISSIONSMANAGECUSTOMPERMISSIONS {
 sql: ${TABLE}.PERMISSIONSMANAGECUSTOMPERMISSIONS;;
}
dimension: PERMISSIONSCANVERIFYCOMMENT {
 sql: ${TABLE}.PERMISSIONSCANVERIFYCOMMENT;;
}
dimension: PERMISSIONSMANAGEUNLISTEDGROUPS {
 sql: ${TABLE}.PERMISSIONSMANAGEUNLISTEDGROUPS;;
}
dimension: PERMISSIONSSTDAUTOMATICACTIVITYCAPTURE {
 sql: ${TABLE}.PERMISSIONSSTDAUTOMATICACTIVITYCAPTURE;;
}
dimension: PERMISSIONSMODIFYSECUREAGENTS {
 sql: ${TABLE}.PERMISSIONSMODIFYSECUREAGENTS;;
}
dimension: PERMISSIONSINSIGHTSAPPDASHBOARDEDITOR {
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPDASHBOARDEDITOR;;
}
dimension: PERMISSIONSMANAGETWOFACTOR {
 sql: ${TABLE}.PERMISSIONSMANAGETWOFACTOR;;
}
dimension: PERMISSIONSINSIGHTSAPPUSER {
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPUSER;;
}
dimension: PERMISSIONSINSIGHTSAPPADMIN {
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPADMIN;;
}
dimension: PERMISSIONSINSIGHTSAPPELTEDITOR {
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPELTEDITOR;;
}
dimension: PERMISSIONSINSIGHTSAPPUPLOADUSER {
 sql: ${TABLE}.PERMISSIONSINSIGHTSAPPUPLOADUSER;;
}
dimension: PERMISSIONSINSIGHTSCREATEAPPLICATION {
 sql: ${TABLE}.PERMISSIONSINSIGHTSCREATEAPPLICATION;;
}
dimension: PERMISSIONSLIGHTNINGEXPERIENCEUSER {
 sql: ${TABLE}.PERMISSIONSLIGHTNINGEXPERIENCEUSER;;
}
dimension: PERMISSIONSVIEWDATALEAKAGEEVENTS {
 sql: ${TABLE}.PERMISSIONSVIEWDATALEAKAGEEVENTS;;
}
dimension: PERMISSIONSCONFIGCUSTOMRECS {
 sql: ${TABLE}.PERMISSIONSCONFIGCUSTOMRECS;;
}
dimension: PERMISSIONSSUBMITMACROSALLOWED {
 sql: ${TABLE}.PERMISSIONSSUBMITMACROSALLOWED;;
}
dimension: PERMISSIONSBULKMACROSALLOWED {
 sql: ${TABLE}.PERMISSIONSBULKMACROSALLOWED;;
}
dimension: PERMISSIONSSHAREINTERNALARTICLES {
 sql: ${TABLE}.PERMISSIONSSHAREINTERNALARTICLES;;
}
dimension: PERMISSIONSMANAGESESSIONPERMISSIONSETS {
 sql: ${TABLE}.PERMISSIONSMANAGESESSIONPERMISSIONSETS;;
}
dimension: PERMISSIONSMANAGETEMPLATEDAPP {
 sql: ${TABLE}.PERMISSIONSMANAGETEMPLATEDAPP;;
}
dimension: PERMISSIONSUSETEMPLATEDAPP {
 sql: ${TABLE}.PERMISSIONSUSETEMPLATEDAPP;;
}
dimension: PERMISSIONSSENDANNOUNCEMENTEMAILS {
 sql: ${TABLE}.PERMISSIONSSENDANNOUNCEMENTEMAILS;;
}
dimension: PERMISSIONSCHATTEREDITOWNPOST {
 sql: ${TABLE}.PERMISSIONSCHATTEREDITOWNPOST;;
}
dimension: PERMISSIONSCHATTEREDITOWNRECORDPOST {
 sql: ${TABLE}.PERMISSIONSCHATTEREDITOWNRECORDPOST;;
}
dimension: PERMISSIONSSALESANALYTICSUSER {
 sql: ${TABLE}.PERMISSIONSSALESANALYTICSUSER;;
}
dimension: PERMISSIONSADMINANALYTICSUSER {
 sql: ${TABLE}.PERMISSIONSADMINANALYTICSUSER;;
}
dimension: PERMISSIONSSERVICEANALYTICSUSER {
 sql: ${TABLE}.PERMISSIONSSERVICEANALYTICSUSER;;
}
dimension: PERMISSIONSCREATEAUDITFIELDS {
 sql: ${TABLE}.PERMISSIONSCREATEAUDITFIELDS;;
}
dimension: PERMISSIONSUPDATEWITHINACTIVEOWNER {
 sql: ${TABLE}.PERMISSIONSUPDATEWITHINACTIVEOWNER;;
}
dimension: PERMISSIONSWAVETABULARDOWNLOAD {
 sql: ${TABLE}.PERMISSIONSWAVETABULARDOWNLOAD;;
}
dimension: PERMISSIONSAUTOMATICACTIVITYCAPTURE {
 sql: ${TABLE}.PERMISSIONSAUTOMATICACTIVITYCAPTURE;;
}
dimension: PERMISSIONSIMPORTCUSTOMOBJECTS {
 sql: ${TABLE}.PERMISSIONSIMPORTCUSTOMOBJECTS;;
}
dimension: PERMISSIONSDELEGATEDTWOFACTOR {
 sql: ${TABLE}.PERMISSIONSDELEGATEDTWOFACTOR;;
}
dimension: PERMISSIONSCHATTERCOMPOSEUICODESNIPPET {
 sql: ${TABLE}.PERMISSIONSCHATTERCOMPOSEUICODESNIPPET;;
}
dimension: PERMISSIONSSELECTFILESFROMSALESFORCE {
 sql: ${TABLE}.PERMISSIONSSELECTFILESFROMSALESFORCE;;
}
dimension: PERMISSIONSMODERATENETWORKUSERS {
 sql: ${TABLE}.PERMISSIONSMODERATENETWORKUSERS;;
}
dimension: PERMISSIONSMERGETOPICS {
 sql: ${TABLE}.PERMISSIONSMERGETOPICS;;
}
dimension: PERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBETOLIGHTNINGREPORTS;;
}
dimension: PERMISSIONSMANAGEPVTRPTSANDDASHBDS {
 sql: ${TABLE}.PERMISSIONSMANAGEPVTRPTSANDDASHBDS;;
}
dimension: PERMISSIONSALLOWLIGHTNINGLOGIN {
 sql: ${TABLE}.PERMISSIONSALLOWLIGHTNINGLOGIN;;
}
dimension: PERMISSIONSCAMPAIGNINFLUENCE2 {
 sql: ${TABLE}.PERMISSIONSCAMPAIGNINFLUENCE2;;
}
dimension: PERMISSIONSVIEWDATAASSESSMENT {
 sql: ${TABLE}.PERMISSIONSVIEWDATAASSESSMENT;;
}
dimension: PERMISSIONSREMOVEDIRECTMESSAGEMEMBERS {
 sql: ${TABLE}.PERMISSIONSREMOVEDIRECTMESSAGEMEMBERS;;
}
dimension: PERMISSIONSCANAPPROVEFEEDPOST {
 sql: ${TABLE}.PERMISSIONSCANAPPROVEFEEDPOST;;
}
dimension: PERMISSIONSADDDIRECTMESSAGEMEMBERS {
 sql: ${TABLE}.PERMISSIONSADDDIRECTMESSAGEMEMBERS;;
}
dimension: PERMISSIONSALLOWVIEWEDITCONVERTEDLEADS {
 sql: ${TABLE}.PERMISSIONSALLOWVIEWEDITCONVERTEDLEADS;;
}
dimension: PERMISSIONSSHOWCOMPANYNAMEASUSERBADGE {
 sql: ${TABLE}.PERMISSIONSSHOWCOMPANYNAMEASUSERBADGE;;
}
dimension: PERMISSIONSACCESSCMC {
 sql: ${TABLE}.PERMISSIONSACCESSCMC;;
}
dimension: PERMISSIONSVIEWHEALTHCHECK {
 sql: ${TABLE}.PERMISSIONSVIEWHEALTHCHECK;;
}
dimension: PERMISSIONSMANAGEHEALTHCHECK {
 sql: ${TABLE}.PERMISSIONSMANAGEHEALTHCHECK;;
}
dimension: PERMISSIONSPACKAGING2 {
 sql: ${TABLE}.PERMISSIONSPACKAGING2;;
}
dimension: PERMISSIONSMANAGECERTIFICATES {
 sql: ${TABLE}.PERMISSIONSMANAGECERTIFICATES;;
}
dimension: PERMISSIONSCREATEREPORTINLIGHTNING {
 sql: ${TABLE}.PERMISSIONSCREATEREPORTINLIGHTNING;;
}
dimension: PERMISSIONSPREVENTCLASSICEXPERIENCE {
 sql: ${TABLE}.PERMISSIONSPREVENTCLASSICEXPERIENCE;;
}
dimension: PERMISSIONSHIDEREADBYLIST {
 sql: ${TABLE}.PERMISSIONSHIDEREADBYLIST;;
}
dimension: PERMISSIONSUSESMARTDATADISCOVERY {
 sql: ${TABLE}.PERMISSIONSUSESMARTDATADISCOVERY;;
}
dimension: PERMISSIONSGETSMARTDATADISCOVERY {
 sql: ${TABLE}.PERMISSIONSGETSMARTDATADISCOVERY;;
}
dimension: PERMISSIONSCREATEUPDATESDDDATASET {
 sql: ${TABLE}.PERMISSIONSCREATEUPDATESDDDATASET;;
}
dimension: PERMISSIONSCREATEUPDATESDDSTORY {
 sql: ${TABLE}.PERMISSIONSCREATEUPDATESDDSTORY;;
}
dimension: PERMISSIONSMANAGESMARTDATADISCOVERY {
 sql: ${TABLE}.PERMISSIONSMANAGESMARTDATADISCOVERY;;
}
dimension: PERMISSIONSSHARESMARTDATADISCOVERYSTORY {
 sql: ${TABLE}.PERMISSIONSSHARESMARTDATADISCOVERYSTORY;;
}
dimension: PERMISSIONSMANAGESMARTDATADISCOVERYMODEL {
 sql: ${TABLE}.PERMISSIONSMANAGESMARTDATADISCOVERYMODEL;;
}
dimension: PERMISSIONSLISTEMAILSEND {
 sql: ${TABLE}.PERMISSIONSLISTEMAILSEND;;
}
dimension: PERMISSIONSFEEDPINNING {
 sql: ${TABLE}.PERMISSIONSFEEDPINNING;;
}
dimension: PERMISSIONSCHANGEDASHBOARDCOLORS {
 sql: ${TABLE}.PERMISSIONSCHANGEDASHBOARDCOLORS;;
}
dimension: PERMISSIONSIOTUSER {
 sql: ${TABLE}.PERMISSIONSIOTUSER;;
}
dimension: PERMISSIONSMANAGERECOMMENDATIONSTRATEGIES {
 sql: ${TABLE}.PERMISSIONSMANAGERECOMMENDATIONSTRATEGIES;;
}
dimension: PERMISSIONSMANAGEPROPOSITIONS {
 sql: ${TABLE}.PERMISSIONSMANAGEPROPOSITIONS;;
}
dimension: PERMISSIONSCLOSECONVERSATIONS {
 sql: ${TABLE}.PERMISSIONSCLOSECONVERSATIONS;;
}
dimension: PERMISSIONSSUBSCRIBEREPORTROLESGRPS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEREPORTROLESGRPS;;
}
dimension: PERMISSIONSSUBSCRIBEDASHBOARDROLESGRPS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEDASHBOARDROLESGRPS;;
}
dimension: PERMISSIONSUSEWEBLINK {
 sql: ${TABLE}.PERMISSIONSUSEWEBLINK;;
}
dimension: PERMISSIONSHASUNLIMITEDNBAEXECUTIONS {
 sql: ${TABLE}.PERMISSIONSHASUNLIMITEDNBAEXECUTIONS;;
}
dimension: PERMISSIONSVIEWONLYEMBEDDEDAPPUSER {
 sql: ${TABLE}.PERMISSIONSVIEWONLYEMBEDDEDAPPUSER;;
}
dimension: PERMISSIONSVIEWALLACTIVITIES {
 sql: ${TABLE}.PERMISSIONSVIEWALLACTIVITIES;;
}
dimension: PERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEREPORTTOOTHERUSERS;;
}
dimension: PERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER {
 sql: ${TABLE}.PERMISSIONSLIGHTNINGCONSOLEALLOWEDFORUSER;;
}
dimension: PERMISSIONSSUBSCRIBEREPORTSRUNASUSER {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEREPORTSRUNASUSER;;
}
dimension: PERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBETOLIGHTNINGDASHBOARDS;;
}
dimension: PERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS {
 sql: ${TABLE}.PERMISSIONSSUBSCRIBEDASHBOARDTOOTHERUSERS;;
}
dimension: PERMISSIONSCREATELTNGTEMPINPUB {
 sql: ${TABLE}.PERMISSIONSCREATELTNGTEMPINPUB;;
}
dimension: PERMISSIONSTRANSACTIONALEMAILSEND {
 sql: ${TABLE}.PERMISSIONSTRANSACTIONALEMAILSEND;;
}
dimension: PERMISSIONSCREATELTNGTEMPFOLDER {
 sql: ${TABLE}.PERMISSIONSCREATELTNGTEMPFOLDER;;
}
dimension: PERMISSIONSAPEXRESTSERVICES {
 sql: ${TABLE}.PERMISSIONSAPEXRESTSERVICES;;
}
dimension: PERMISSIONSENABLECOMMUNITYAPPLAUNCHER {
 sql: ${TABLE}.PERMISSIONSENABLECOMMUNITYAPPLAUNCHER;;
}
dimension: PERMISSIONSGIVERECOGNITIONBADGE {
 sql: ${TABLE}.PERMISSIONSGIVERECOGNITIONBADGE;;
}
dimension: PERMISSIONSLTNGPROMORESERVED01USERPERM {
 sql: ${TABLE}.PERMISSIONSLTNGPROMORESERVED01USERPERM;;
}
dimension: PERMISSIONSCANEDITDATAPREPRECIPE {
 sql: ${TABLE}.PERMISSIONSCANEDITDATAPREPRECIPE;;
}
dimension: PERMISSIONSADDANALYTICSREMOTECONNECTIONS {
 sql: ${TABLE}.PERMISSIONSADDANALYTICSREMOTECONNECTIONS;;
}
dimension: PERMISSIONSMANAGESURVEYS {
 sql: ${TABLE}.PERMISSIONSMANAGESURVEYS;;
}
dimension: PERMISSIONSRECORDVISIBILITYAPI {
 sql: ${TABLE}.PERMISSIONSRECORDVISIBILITYAPI;;
}
dimension: PERMISSIONSVIEWROLES {
 sql: ${TABLE}.PERMISSIONSVIEWROLES;;
}
dimension: PERMISSIONSSMARTDATADISCOVERYFORCOMMUNITY {
 sql: ${TABLE}.PERMISSIONSSMARTDATADISCOVERYFORCOMMUNITY;;
}
dimension: PERMISSIONSCANMANAGEMAPS {
 sql: ${TABLE}.PERMISSIONSCANMANAGEMAPS;;
}
dimension: PERMISSIONSSTORYONDSWITHPREDICATE {
 sql: ${TABLE}.PERMISSIONSSTORYONDSWITHPREDICATE;;
}
dimension: PERMISSIONSMODIFYDATACLASSIFICATION {
 sql: ${TABLE}.PERMISSIONSMODIFYDATACLASSIFICATION;;
}
dimension: PERMISSIONSPRIVACYDATAACCESS {
 sql: ${TABLE}.PERMISSIONSPRIVACYDATAACCESS;;
}
dimension: PERMISSIONSQUERYALLFILES {
 sql: ${TABLE}.PERMISSIONSQUERYALLFILES;;
}
dimension: PERMISSIONSMODIFYMETADATA {
 sql: ${TABLE}.PERMISSIONSMODIFYMETADATA;;
}
dimension: USERLICENSEID {
 sql: ${TABLE}.USERLICENSEID;;
}
dimension: USERTYPE {
 sql: ${TABLE}.USERTYPE;;
}
dimension: CREATEDDATE {
 sql: ${TABLE}.CREATEDDATE;;
}
dimension: CREATEDBYID {
 sql: ${TABLE}.CREATEDBYID;;
}
dimension: LASTMODIFIEDDATE {
 sql: ${TABLE}.LASTMODIFIEDDATE;;
}
dimension: LASTMODIFIEDBYID {
 sql: ${TABLE}.LASTMODIFIEDBYID;;
}
dimension: SYSTEMMODSTAMP {
 sql: ${TABLE}.SYSTEMMODSTAMP;;
}
dimension: DESCRIPTION {
 sql: ${TABLE}.DESCRIPTION;;
}
dimension: LASTVIEWEDDATE {
 sql: ${TABLE}.LASTVIEWEDDATE;;
}
dimension: LASTREFERENCEDDATE {
 sql: ${TABLE}.LASTREFERENCEDDATE;;
}
}